### PR TITLE
Issue #13588 input number max length ignores paste

### PR DESCRIPTION
**Pull request by dylansyoung**
Fixes issue #13588

### CODE REVIEW

**Comment by ashikjs** [comment]
@dylansyoung  can you make this change with in one commit ?

**Comment by dylansyoung** [comment]
@ashikjs yes would you like me to submit a new PR?

**Comment by ashikjs** [comment]
No, Just squash commits and force push here. 

[How do I squash my last N commits together?](https://stackoverflow.com/questions/5189560/how-do-i-squash-my-last-n-commits-together)

**Comment by dylansyoung** [comment]
@ashikjs is that what you want?

**Comment by dylansyoung** [comment]
submitting a new PR for this with one commit [here](https://github.com/primefaces/primeng/pull/13594)

**Pull request closed without merging**
