### PR TITLE
Adds new feature - Picklist selectable

### PR DESCRIPTION
**Pull request by EnricoMessall**
### Feature Requests
Support Selectable state in PickList equal to DragDrop.

Matching discussion with more informations:
https://github.com/orgs/primefaces/discussions/2334

### CODE REVIEW

**Comment by rosenthalj** [comment]
This change is incompatible with Angular v17.   Currently PrimeNG 17.8.x is compatible with both Angular v17 and Angular v18

```
  "peerDependencies": {
    "@angular/core": "^17.0.0 || ^18.0.0",
    "@angular/common": "^17.0.0 || ^18.0.0",
    "@angular/forms": "^17.0.0 || ^18.0.0",
    "rxjs": "^6.0.0 || ^7.8.1",
    "zone.js": "~0.14.0"
  },
```

**Comment by EnricoMessall** [comment]
@rosenthalj Do you mean because of https://v17.angular.io/guide/control_flow?

Its developer preview in v17 and should work already, since it has not changed for v18. I also have a v17 project where i already use the new control flow

**Comment by rosenthalj** [comment]
> @rosenthalj Do you mean because of https://v17.angular.io/guide/control_flow?
> 
> Its developer preview in v17 and should work already, since it has not changed for v18. I also have a v17 project where i already use the new control flow

@EnricoMessall 
You're right,  my bad.  PR #16045  should be compatible with both Angular v17 and Angular v18.  This is the first change I've reviewed that used control_flow which is supported in Anuglar v17.

**Comment by cetincakiroglu** [comment]
Hi,

This PR will be reviewed in v18. Thanks for the effort and support!

**Comment by mertsincan** [comment]
Hi @EnricoMessall,

Thanks a lot for your contribution! Unfortunately, this PR has conflicts, so I cannot merge it. Could you please create a new PR and open a corresponding issue for this PR? Additionally, it would be better if the new PR does not include demos for this new feature.

Best Regards,

**Pull request closed without merging**
