### PR TITLE
DatePicker : 12 hour format validation error

### LINKED ISSUE #1673: DatePIcker:  12 hourformat validation error
When hourformat set to "12" and selected date is in "PM" , change the hour to 12 in  inputfield and the date changes to AM and the date in the input filed show PM,

When the time is in "AM" and edit hour to 12 it sets as a 12"00 AM and the value is 00:00.

When the date is set to 12:00PM, change the am/pm to "AM" and date set to 12:00 am

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

**Current behavior**

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.X

* **PrimeNG version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

### PR DESCRIPTION
**Pull request by harilal**
###Defect Fixes
#1673 
Added proper validatio in Am/PM change. In valid date will fire am error.
When the time is 12:00 PM and change to AM using the am/pm selector will change it to 00:00 AM.

###Feature Requests
Due to company policy, we are unable to accept feature request PRs with significant changes as such cases has to be implemented by our team following our own processes.
Smaller scaled feature implementations such as adding a property to a component will be considered for merging.

### CODE REVIEW

**Comment by cagataycivici** [comment]
There is a conflict now, what is the actual problem? I don't think 00 am is valid.

**Comment by harilal** [comment]
@cagataycivici  the issue is with 12 hourformat. I will test it with new version and resolve the conflict for the new version. The main issue is some thing like if you choose an hour more than 12 in the edit input it should throw an error instead it gives a valida date with the time of 12:00. Other is if you change the date in the edit field when the time is in "PM" and you changed the hour to 12 it will switch to AM in UI and not updating the edit field. 
If the date in edit field is wrong it should throw an error instead of a valid date.

**Comment by harilal** [comment]
@cagataycivici the conflict has been resolved. 
The major issue is ,the user edit the hour of the time to 12 when the time is in PM it's automatically changes to AM . Actually there is no 12:30 AM. Once its past 12 , its become 00:30. Or else it should throw an invalid date. And also when an hour changed to greater than 12 it should throw an invalid date, since its an 12 hour format.

**Comment by harilal** [comment]
I will update and fix it with latest one and initiate new pull request.

**Pull request closed without merging**
