### PR TITLE
DataTable filter loop with lazy loading

### PR DESCRIPTION
**Pull request by bogdanvaduva**
I've added the filtered property which should solve the issue with filter() loop.

### CODE REVIEW

**Comment by cagataycivici** [comment]
What is the original issue with loop?

**Comment by bogdanvaduva** [comment]
It stays in a loop if you use lazy loading and filter.

**Comment by maleet** [comment]
For me looping occurs because of  ngDoCheck. I get new data so there are changes with diff checking. And if there are filters also then it's in loop... new data from backend, ngDoCheck with changes and filter method call.

**Comment by mwaltersva** [comment]
#1136 Just tagging the original issue

**Comment by cagataycivici** [comment]
This turned out to be a regression of #986 which has better solutions like resetting table when actual data changes, so reverting that to fix this. Logged at #1170

**Comment by bogdanvaduva** [comment]
Thanks.
I think there is also a problem with hasFilter() because returns true even if the filters are empty (I means when you enter something in a filter and then you delete it).

**Comment by dan-madaket** [comment]
@cagataycivici There is another regression on this issue.  I'm having this problem in primeng 4.0.0-rc.2.

**Pull request closed without merging**
