### PR TITLE
feat(primeng/p-badge): rework dynamic property rerender for directive

### LINKED ISSUE #12736: Badge directive with badgeDisabled condition not working
### Describe the bug

The following does not work when `user.notifications` changes value to/from zero.

```html
<i class="pi pi-bell" pBadge [value]="user.notifications" [badgeDisabled]="user.notifications === 0"></i>
```

If the initial result from `user.notifications === 0` is `true`, then the badge will remain hidden even if the value of user.notifications changes, so `user.notifications === 0` result is updated to `false`, the badge is still hidden, but at that point should be shown. 

### Environment

PrimeNG 14.2.3

### Reproducer

_No response_

### Angular version

14

### PrimeNG version

14.2.3

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.16.0

### Browser(s)

Chrome

### Steps to reproduce the behavior

_No response_

### Expected behavior

badgeDisabled should reevaluate when a new value is passed to it.

### LINKED ISSUE #12959: Avatar and Badge use the same size attribute
### Describe the bug

When using the Avatar-Component together with its Badge-Directive they use the same size attribute.
Setting the Avatars size to xlarge also enlarges its Badge.

### Environment

Angular & PrimeNG 15

### Reproducer

https://primeng.org/avatar#icon

### Angular version

15

### PrimeNG version

15

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18

### Browser(s)

_No response_

### Steps to reproduce the behavior

`<p-avatar icon="pi pi-user" pBadge value="4" severity="success" styleClass="mr-2" size="large"></p-avatar>`

### Expected behavior

It should be possible to resize one without the other.

### PR DESCRIPTION
**Pull request by volvachev**
### Defect Fixes
Fixes #12736 
Fixes #12959

### CODE REVIEW

**Comment by volvachev** [comment]
Hi, @cetincakiroglu can you look?

**Comment by ProfEibe** [comment]
@cetincakiroglu anything we can do to get this merged?

**Comment by cetincakiroglu** [comment]
Hi @volvachev,

Could you please resolve the conflicts and instead of removing the size property from badge which leads to breaking change, could you please deprecate it and add the new property?

I'll merge it after these changes.

**Comment by volvachev** [comment]
> Hi @volvachev,
> 
> Could you please resolve the conflicts and instead of removing the size property from badge which leads to breaking change, could you please deprecate it and add the new property?
> 
> I'll merge it after these changes.

Hi, I've updated

**Pull request merged**
