### PR TITLE
Bug fix: Radio button label not disabling

### PR DESCRIPTION
**Pull request by derekbar90**
This merge addresses an issue with the radio button component, allowing a user to select a radio value through the label although the input was disabled. 

Signed-off-by: Derek Barrera <derekbarrera@gmail.com>

### CODE REVIEW

**Comment by derekbar90** [comment]
Fixes Bug: #983

**Comment by cagataycivici** [comment]
Will apply a slightly different fix

**Comment by deveshsinghal22** [comment]
any update for this.
I am still facing this issue

**Comment by nadhir-falta** [comment]
Still getting this issue on 5.2.4

**Pull request closed without merging**
