### PR TITLE
Fixed bug #4915

### PR DESCRIPTION
**Pull request by pantonis**

### CODE REVIEW

**Comment by cagataycivici** [comment]
Resetting page is by design, these should be options at least, not all user may like it.

**Comment by pantonis** [comment]
@cagataycivici I have vast experience with business intelligence and tabular data for years.  I have never seen this behavior before.
In any case If you wish to keep this behavior It would be good to have it optional as you said. I will be waiting for this change. Thanks

**Comment by jarinwhite** [comment]
Seconding @pantonis, the leading datagrid (ag-Grid) does not reset the page when sorting. See their [Pagination example](https://www.ag-grid.com/javascript-grid-pagination/). The current behavior of TurboTable is simply counter-intuitive to almost every enterprise-grade datagrid I've used. 

Would be good to at least make this an option.

**Comment by pantonis** [comment]
Yes. For me every time I npm install have to go and manually change it. Sometimes it does not AOT build because of my changes.

Hope @cagataycivici changes this.

**Pull request closed without merging**
