### PR TITLE
Fix #14550: Chips. Fixed case sensitive chips validation

### LINKED ISSUE #14550: Component: Chips. Duplicate validation is case sensitive
### Describe the bug

Currently, chip validation in `p-chips` component is case sensitive, it means that `test@test.com` and `Test@test.com` (or `test` and `Test`) are considered different values and don't treated as duplication. 

### Environment

Chrome

### Reproducer

_No response_

### Angular version

17.0.2

### PrimeNG version

17.3.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.10.0

### Browser(s)

_No response_

### Steps to reproduce the behavior

1. Go to `Chips`
2. Set `[allowDuplicate]=false`
3. Type `test` and hit `Enter`
4. Type `Test` and hit `Enter`
5. Observe result

### Expected behavior

Component should only have `test` value. 
`Test` should be filtered out

### PR DESCRIPTION
**Pull request by AndrewAKovalenko**
### Defect Fixes
Fixes https://github.com/primefaces/primeng/issues/14550

### CODE REVIEW

**Comment by AndrewAKovalenko** [comment]
Also, to save backward compatibility, new `@Input` can be introduced.
 Something like `@Input() caseInsensitiveDuplication = false`

**Comment by mertsincan** [comment]
Thanks a lot for your contribution! Yes, a new prop might be better. If you update PR, I'll merge it asap.

Best Regards,

**Comment by AndrewAKovalenko** [comment]
Added new input `caseSensitiveDuplication` with test, updated docs

**Comment by mertsincan** [comment]
Good job! Thanks a lot for your contribution!

**Pull request merged**
