### PR TITLE
fix of left percent offset for (range) slider

### PR DESCRIPTION
**Pull request by berc**
fix of left percent offset for (range) slider

### CODE REVIEW

**Comment by cagataycivici** [comment]
What is the actual issue here?

**Comment by berc** [comment]
slider position is moved to the right side by min value, because bad percentage calculation. Percentage for "left" css translate begins not from 0, but from percentage of min value from zero and also slider button position on right side is out of the 100 % and out of the slider component.

**Comment by cagataycivici** [comment]
How can we replicate the issue? Could you please post a simple test code for it?

**Comment by berc** [comment]
set min to 500 and max to 1000 and you should see that slider is going out of the component.

**Comment by cagataycivici** [comment]
Ok, I'll try it tomorrow and review the PR. Thank you.

**Comment by cagataycivici** [comment]
The PR has not fixed anything so reverting, we'll fix this on our side, thank you.

**Pull request merged**
