### PR TITLE
Fixed #15852 - Table: Frozen columns are displaced

### LINKED ISSUE #15852: Table: Frozen columns are displaced
### Describe the bug

In a table with many columns, of which also a large number are frozen, the placement of the fixed columns is totally messed up.
Headers are placed out of order, and row cells are not frozen at all

### Environment

Chrome
Edge
Firefox

### Reproducer

https://github-8nkwy5.stackblitz.io

### Angular version

17.3.9

### PrimeNG version

17.18.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

22.2.0

### Browser(s)

_No response_

### Steps to reproduce the behavior

1. Open the app
2. Scroll the table horizontally
3. Frozen columns scroll with the table

### Expected behavior

Frozen columns should remain fixed at their position, no matter how many columns are frozen, and no matter how large or small the screen is.

### PR DESCRIPTION
**Pull request by ranthonissen**
Fixed #15852 - Table: Frozen columns are displaced

### CODE REVIEW

**Comment by bartlomiej-dobosz** [comment]
Hi @ranthonissen 
I haven't run your code but I just wanted to mention that the changes you made mostly undo the changes from this #15302 issue. Please check if your changes have not reversed that bug.

If so here is my qickfix:
```ts
recalculateColumns() {
        const siblings = DomHandler.siblings(this.el.nativeElement);
        const index = DomHandler.index(this.el.nativeElement);
        const time = this.alignFrozen === 'right' ? (siblings.length - index + 1) * 50 : (index + 1) * 50; //this line

        setTimeout(() => {
            this.updateStickyPosition();
        }, time);
        this.updateStickyPosition();
}
```

**Comment by ranthonissen** [comment]
Hi @bartlomiej-dobosz,

As far as I am familiar with the code, the fix provided in #15302 did not solve the problem, but only delayed the calculation of the column position, causing this issue #15852.
The underlying issue was that `DomHandler.getOuterWidth(next)` and `DomHandler.getOuterWidth(prev)` in the `updateStickyPosition()` function always returned 0, because of the table not being rendered/displayed at the time of calculation.

I think this fix resolves that issue, making the delayed execution of `updateStickyPosition()` unnecessary.

**Comment by ranthonissen** [comment]
I haven't tested it myself, but i might also fix #15816, as it is the same code portion that seems to cause that issue

**Comment by bartlomiej-dobosz** [comment]
I found bug. When you add more columns and start sorting, this happens:

image

**Comment by ranthonissen** [comment]
@bartlomiej-dobosz
I'm unable to reproduce the behavior you show in your screenshot .
Can you provide me with code that shows this bug?

chrome_wnG8ynj2Mg

**Comment by ranthonissen** [comment]
@bartlomiej-dobosz Any update on this PR?

The issues on the frozen columns are a showstopper for our team.
So if there is any way I can help and speed things up (with this and related frozen table column issues), don't hesitate to reach out to me, and I will see how I can help.

I think some more issues were introduced by #15302. So I think it might be a good idea to revert these changes, start over from that point with another approach, and closely keep an eye on the fix for the original issue #15303, and making sure no new issues get introduced.

**Comment by bartlomiej-dobosz** [comment]
Sorry I forgot to reply here.
I think the error I described above was the result of my mistake. Ignore it.
In my project I had to hack sorting to add a third state (ASC, DESC and NONE). And this affects your solution.

**Pull request merged**
