### PR TITLE
Readonly arrays for p-dropdown and p-splitbutton

### LINKED ISSUE #8609: readonly modifier for options at p-dropdown and model at p-splitButton
[ ] bug report => Search github for a similar issue or PR before submitting
[x ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Dropdown (p-dropdown) has input "options: any[]".
Splitbutton (p-splitButton) has input "model: MenuItem[]".

**Expected behavior**
These components do not change input values, so it would be good to make them readonly:
- options: readonly any[]
- model: readonly MenuItem[]

**What is the motivation / use case for changing the behavior?**
Right now, we cannot pass readonly arrays with the new strictTemplates Angular 9 mode.

* **Angular version:** 5.X
Angular 9.0.5

* **PrimeNG version:** 5.X
PrimeNG 0.0

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript 3.7

### PR DESCRIPTION
**Pull request by papb**
Fixes #8609

### CODE REVIEW

**Comment by papb** [comment]
I was hoping to see automated tests running when I opened the PR, but apparently there aren't any.

**Comment by worming004** [comment]
It correct my current problem. Good !

I am thinking to add 1 unit test per modified component, to ensure no regression on readonly collections.
I would have time to do that before Monday.

**Comment by papb** [comment]
Ready for review!

**Comment by papb** [comment]
Still relevant. Still waiting for someone to review and merge.

**Comment by papb** [comment]
Please reopen

**Pull request closed without merging**
