### PR TITLE
6970 & 7130- Fixed error when using Calendar month view with range or multi selection.

### LINKED ISSUE #6970: p-calendar view="month" selectionMode="range"  doesn't work
Calendar.html:64 ERROR TypeError: this.value.getDate is not a function
    at Calendar.push../node_modules/primeng/components/calendar/calendar.js.Calendar.isMonthSelected (calendar.js:582)
    at Object.eval [as updateDirectives] (Calendar.html:64)
    at Object.debugUpdateDirectives [as updateDirectives] (core.js:11061)
    at checkAndUpdateView (core.js:10458)
    at callViewAction (core.js:10699)
    at execEmbeddedViewsAction (core.js:10662)
    at checkAndUpdateView (core.js:10459)
    at callViewAction (core.js:10699)
    at execEmbeddedViewsAction (core.js:10662)
    at checkAndUpdateView (core.js:10459)

### PR DESCRIPTION
**Pull request by rtaft**
###Defect Fixes
#6970 and #7130

### CODE REVIEW

**Comment by cagataycivici** [comment]
Tracked at https://github.com/primefaces/primeng/issues/7130

**Comment by mertsincan** [comment]
Sorry for misunderstanding! Thanks a lot for the PR!

**Comment by mertsincan** [comment]
I made some changes in your PR; https://github.com/primefaces/primeng/commit/2b2a8ea0005f736208844f653cbb7efed11a2818

**Comment by rtaft** [comment]
Thanks you!  I tested your changes for range selection and it works good.

**Pull request merged**
