### PR TITLE
[FIX] #14600 Add Disabled state for icon button 

### PR DESCRIPTION
**Pull request by pouyababaie**
#14600 

i added this feature , I'm guessing a lot of people felt the need of this.

image

### CODE REVIEW

**Comment by cdskill** [comment]
+1 should be merged this issue is here since 2019

**Comment by cetincakiroglu** [comment]
Hi,

Instead of changing functionality of current `disabled` attribute, could you please add two new inputs so users can disable it totally or disable them by their choice. It should be like this:

1-) All disabled, if user sets disabled as true, component will be disabled completely (this is for backward compatibility).
```
<p-splitButton [disabled]="true"></p-splitButton>
```

2-) Add new `buttonDisabled` and `menuButtonDisabled` input properties.

```
// that one should only disable the button of the component.
<p-splitButton [buttonDisabled]="true"></p-splitButton>

// that one should only disable the menu button of the component.
<p-splitButton [menuButtonDisabled]="true"></p-splitButton>
```

3-) If they are all used together, the `disabled` property should supersede `menuButtonDisabled` and `buttonDisabled` properties.

I'll merge after these changes. In this way, we keep the functionality of `disabled` and introduce two new input props if anyone needs to use.

**Comment by pouyababaie** [comment]
> Hi,
> 
> 
> 
> Instead of changing functionality of current `disabled` attribute, could you please add two new inputs so users can disable it totally or disable them by their choice. It should be like this:
> 
> 
> 
> 1-) All disabled, if user sets disabled as true, component will be disabled completely (this is for backward compatibility).
> 
> ```
> 
> <p-splitButton [disabled]="true"></p-splitButton>
> 
> ```
> 
> 
> 
> 2-) Add new `buttonDisabled` and `menuButtonDisabled` input properties.
> 
> 
> 
> ```
> 
> // that one should only disable the button of the component.
> 
> <p-splitButton [buttonDisabled]="true"></p-splitButton>
> 
> 
> 
> // that one should only disable the menu button of the component.
> 
> <p-splitButton [menuButtonDisabled]="true"></p-splitButton>
> 
> ```
> 
> 
> 
> 3-) If they are all used together, the `disabled` property should supersede `menuButtonDisabled` and `buttonDisabled` properties.
> 
> 
> 
> I'll merge after these changes. In this way, we keep the functionality of `disabled` and introduce two new input props if anyone needs to use.
> 
> 
> 
> 
> 
> **Please tag me after the changes so I don't miss the PR.**

I will work on it 👍🏻

**Comment by pouyababaie** [comment]
@[cetincakiroglu](https://github.com/cetincakiroglu)

I added the requested state for disabled button but i'm not sure i did it the right way. i would be very happy to see your comments on this commit. if there is a better way to solve this issue , i'd like to hear it.

image

**Pull request merged**
