### PR TITLE
Fix #13086 - KeyFilter.pattern type

### LINKED ISSUE #13086: Wrong type definition of KeyFilter.pKeyFilter (pattern)
### Describe the bug

The `pKeyFilter` directive currently accepts only a `string` as pattern (aliased to `pKeyFilter`).
This is misleading and should also match a `RegExp`.

### Environment

.

### Reproducer

_No response_

### Angular version

16.0.2

### PrimeNG version

16.0.0-rc.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.14.1

### Browser(s)

_No response_

### Steps to reproduce the behavior

_No response_

### Expected behavior

_No response_

### PR DESCRIPTION
**Pull request by Menecats**
This PR fixes issue #13086 by allowing `RegExp` as an input value and restricting the `string` type to only the valid patterns.

Moreover adds support for *nullish* values to prevent undefined value access if the pattern is not immediately set. (e.g. via `async` pipe)

### CODE REVIEW

**Comment by SoyDiego** [comment]
Hope they accept that soon

**Review by cetincakiroglu — APPROVED** [review]

**Comment by cetincakiroglu** [comment]
Hi, could you please re-open that PR so I can merge it.

**Comment by Menecats** [comment]
Hi  @cetincakiroglu, I still see this PR (13086) as `Open`

**Comment by mertsincan** [comment]
Thanks a lot for your contribution!

Best Regards,

**Pull request merged**
