### PR TITLE
Fix #14160 Update confirmdialog.ts

### LINKED ISSUE #14160: Component: ConfirmDialog
### Describe the bug

The ConfirmDialog supports customization through ng-templates. However when looking at the source code I noticed that not the correct element, ng-container, is used as the templateOutlet for several templates. I have created a PR that resolves this.

### PR

[PR](https://github.com/primefaces/primeng/pull/14154)

### Reproducer

_No response_

### Angular version

16.2.12

### PrimeNG version

16.8.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.x.x

### Browser(s)

_No response_

### Steps to reproduce the behavior

1.) use ngTemplate for ConfirmDialog message and you will notice it will not be rendered correctly once openend.

### Expected behavior

Correct support for ngTemplate for all required elements inside ConfirmDialog

### PR DESCRIPTION
**Pull request by reramjiawan**
Fix #14160 Use ng-container for templateOutlet since ng-template does not work!

### CODE REVIEW

**Comment by SoyDiego** [comment]
> templateOutlet

Thanks for your contribution, Could you put the issue link  that resolves this PR?. If is not exist, create one and then link this PR to the issue :)

**Comment by reramjiawan** [comment]
> > templateOutlet
> 
> Thanks for your contribution, Could you put the issue link that resolves this PR?. If is not exist, create one and then link this PR to the issue :)

Done!

**Review by SoyDiego — APPROVED** [review]

**Comment by reramjiawan** [comment]
> > > > templateOutlet
> > > 
> > > 
> > > Thanks for your contribution, Could you put the issue link that resolves this PR?. If is not exist, create one and then link this PR to the issue :)
> > 
> > 
> > Done!
> 
> Thanks but is not linked yet, you should add `Fix #14160` editing your first message :) and you will see linked here:
> 
> image

Hopefully I did it correctly now. Thanks for the approval!

**Comment by SoyDiego** [comment]
> > > > > templateOutlet
> > > > 
> > > > 
> > > > Thanks for your contribution, Could you put the issue link that resolves this PR?. If is not exist, create one and then link this PR to the issue :)
> > > 
> > > 
> > > Done!
> > 
> > 
> > Thanks but is not linked yet, you should add `Fix #14160` editing your first message :) and you will see linked here:
> > image
> 
> Hopefully I did it correctly now. Thanks for the approval!

Perfect, thanks!

**Pull request closed without merging**
