### PR TITLE
Fix table columns resize when there are frozen columns

### LINKED ISSUE #5751: p-table (turbo table) frozenColumns + resize not working
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
throwing error 
Uncaught TypeError: Cannot read property 'nextElementSibling' of undefined

**Expected behavior**
resizableColumns should work with frozen coloumns

**Minimal reproduction of the problem with instructions**
use frozenColumns , resizableColumns = true

* **Angular version:** 5.2.6

* **PrimeNG version:** 5.2.4

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [TypeScript 2.4.2 ]

* **Node (for AoT issues):** `node --version` =   8.11.1

### PR DESCRIPTION
**Pull request by Dragsaw**
###Defect Fixes

This PR fixes #5751.
After this, frozen columns will not support resizing, but the rest of the columns can be resized.

### CODE REVIEW

**Comment by druha95** [comment]
@Dragsaw, which release will include this fix? I mean version of library

**Comment by Dragsaw** [comment]
@druha95, no idea. As you see, the PR hasn't been accepted yet, so we'll have to wait for that first. 🤞

**Comment by amedvedsy** [comment]
@Dragsaw^ thanks for response. I hope it will be merge asap

**Comment by cagataycivici** [comment]
Fixed with a different approach, thank you.

**Pull request closed without merging**
