### PR TITLE
Fix p-autoComplete: selected item template is not displayed

### LINKED ISSUE #2242: Template for selected item in autocomplete (single selection mode)
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ x ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**

It's already possible to define an "item" template for the suggestions of the autocomplete, but this template is not used for the selected item. The selected item only looks at the "field" attribute, so it can only display 1 property of the object to which the ngModel is bound.

It's also possible to define a "selectedItem" template, but this template only seems to work in multiple selection mode (as stated in the documentation).

I've tried this example:

    <p-autoComplete [(ngModel)]="customer" [suggestions]="customerResults" (completeMethod)="searchCustomers($event)" field="name">
      <template let-customer pTemplate="item">
        {{customer.name}} {{customer.firstname}}
      </template>
      <template let-cusstomer pTemplate="selectedItem">
        {{customer.name}} {{customer.firstname}}
      </template>
    </p-autoComplete>

With this code my selected item only shows the "name" property of my customer-object. If I don't provide the field-property, my selected item is displayed as [object Object].

**Expected behavior**
I expect it to be possible to define a template for the selected item when the autocomplete is in single selection mode. It seems like I'm missing something as no one else seems to be asking this question, but I've tried everything I could find in the documentation, and nothing seemed to work.

**Minimal reproduction of the problem with instructions**

* **Angular version:** ~2.4.0

* **PrimeNG version:** 2.0.1

* **Browser:** [all ]

### PR DESCRIPTION
**Pull request by Tuxio**
### Defect Fixes
Fixes  #2242 #12983

### CODE REVIEW

**Comment by mertsincan** [comment]
@cetincakiroglu Could you please check this PR?

Best Regards,

**Comment by pjlasl** [comment]
Any update on this?

**Comment by LiolluryZ** [comment]
up

**Comment by cetincakiroglu** [comment]
Hi @Tuxio ,

Thank you for taking the time to submit your pull request. We genuinely appreciate your effort and interest in improving our project.

After careful review and consideration, we have decided not to merge your pull request at this time. Please understand that this decision does not reflect negatively on the quality of your work. We value every contribution and understand the effort you've put into it.

However, upon review, we believe that the changes proposed in this pull request may not align with the current goals or direction of the project. Our team is continuously evaluating and prioritizing features and enhancements based on various factors, including project roadmap, user feedback, and technical considerations. selectedItem template support will be implemented for singular input mode also in the future.

We encourage you to continue contributing to the project and to stay engaged with our community. Your input and contributions are valuable, and we look forward to seeing more of your work in the future.

Once again, thank you for your contribution, and please don't hesitate to reach out if you have any questions or would like further feedback.

Best regards,

**Comment by uebelmar** [comment]
@cetincakiroglu the selectedItem Template doesnt work since several major versions. Here someone does the work and fixes it and it is ignored.

**Comment by cetincakiroglu** [comment]
@uebelmar,

selectedItem template is only supported for multiple mode. It's not broken feature, it's not supported in single mode. We've closed the PR because:

1-) Styling becomes broken, and unnecessary borders and outlines can be seen on focus.
2-) Styles should be applied in primeng-sass-theme not in component CSS. Padding and margin values change depending on the applied theme. In this way, they will always be the same.
3-) We can't apply min-width to the styles.
4-) Dom structure changes and it's a breaking change.
5-) Also even the example doesn't work correctly. See the image, you can also see that weird size difference in second image.
6-) It breaks accessibility, overlay shouldn't open by down arrow, also overlay cannot be opened by search, it's a weird behavior.
7-) In the third image, you can enter input simultaneously while the selection is also rendered, which is the default behavior of multiple mode, it doesn't function correctly.

To conclude, if it's the use case, then just use multiple mode with

So it's not ignored, it's reviewed and closed. We can't merge a feature that doesn't function correctly.

Screenshot 2024-03-28 at 09 21 25
Screenshot 2024-03-28 at 09 22 08
Screenshot 2024-03-28 at 09 25 53

**Comment by cetincakiroglu** [comment]
> @cetincakiroglu
> 
> Thank you for taking the time to explain. That of course makes sense. I also saw in another issue that you have support for selectedItem in single mode on the feature list.
> 
> Another thing to think about is that the documentation for the selectedItem template mentions that it is only supported in single mode. In the last few years there have been a few Github issues and StackOverflow articles that have come across this.

Yes we'll update the docs to indicate that it's not supported in single mode

**Pull request closed without merging**
