### PR TITLE
Fixes most components for compatibility with Content-security-Policies that enforce trusted-types

### LINKED ISSUE #12855: PrimeNG doesn't work with Content-security-Policies that enforce trusted-types
### Describe the feature you would like to see added

PrimeNG has multiple issues that make it incompatible with Content-security-Policies that enforce trusted-types.
Most companies I work for have (for good reason) security policies in place that require a CSP that enforces trusted-types. That means, PrimeNG is not allowed to be used with such companies. 

This has been reported before, see e.g this closed issue: https://github.com/primefaces/primeng/issues/11050

Mostly this is because PrimeNG makes assignments to innerHTML all over the code base. In most cases this could be replaced relatively easily with textContent (if it is just textual content that is assigned, also possyble for style elements).

### Is your feature request related to a problem?

The problem is that PrimeNG is incompatible with a COntent-Security-Policy that enforces trusted-types.

### Describe the solution you'd like

Make PrimeNG compatible witrh stricter security policies

### Describe alternatives you have considered

No alternative

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by gerjon-eatch**
### Defect Fixes
Fixes #12855

This fixes most components for compatibility with Content-security-Policies that enforce trusted-types, by using textContent instead of innerHTML where possible.

### CODE REVIEW

**Comment by mertsincan** [comment]
Hi @gerjon-eatch,

Sorry for the delayed response! Could you please update your PR? Then, I'll merge it asap.

Best Regards,

**Comment by mertsincan** [comment]
Hi,

Unfortunately, there seems to be a lot of conflicts. So a new PR might be better. For now, closed. Could you please create a new PR for us? I'll check and merge asap. Thanks a lot for your understanding and contribution!

Best Regards,

**Comment by EmmaLin1019** [comment]
Hi,
Is there any release plan for this issue?
Thanks!

Best regards,

**Comment by vijaycule22** [comment]
Hi, can anyone provide code to resolve this issue for the p-table component?

**Pull request closed without merging**
