### PR TITLE
Fix #6520 - overlayPanel's and dialog's onHide

### LINKED ISSUE #6520: onHide event not triggered in version 6.1.4 for dialog and overlayPanel
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
Current behavior**
The onHide event is NOT triggered anymore even if the panel/dialog is visible

**Expected behavior**
The onHide event should be  triggered as before.

**Minimal reproduction of the problem with instructions**
This simple code can be used tor reproduce the problem:

```
<p-overlayPanel [dismissable]="true" [showCloseIcon]="true" #op [style]="{'width':'320px'}" appendTo="body" (onHide)="hideTest()">
    <h1>CIAO</h1>
</p-overlayPanel>

<button type="text" pButton label="Basic" (click)="op.toggle($event)"></button>
```

and, of course, a hideTest() method should be defined in the Component.

Now click on the button and then close the OveralyPanel... the hideTest method is not called because the onHide event is not emitted.

### PR DESCRIPTION
**Pull request by Hunroll**
###Defect Fixes
Fix #6520 - overlayPanel's and dialog's onHide. Revert previous changes (PR #6471) and suspend calling onOverlayHide event in destructor if overlay is not visible.

###Feature Requests
N/A

### CODE REVIEW

**Comment by coffeetea-synchestra** [comment]
Please merge it, anybody ;(

**Comment by cagataycivici** [comment]
We'll handle it differently, I don't think it makes sense to call onHide at ondestroy e.g. route change.

**Comment by igor04** [comment]
@cagataycivici any changes about `onHide`?

because it looks like `onHide` event is not triggered and there is no references to other issues/pr's

**Comment by rafa-as** [comment]
I think that makes sense to call onHide on destroy because sometimes you can have an ngIf in a component that have a dialog inside and if have some logic when de dialog disappears in this case this logic will not fired.

Please reconsidere this pull request @cagataycivici

**Pull request closed without merging**
