### PR TITLE
account for time format updates and switching am/pm only

### LINKED ISSUE #4486: Time picker displays 00 for hours for 12 hour time (Resubmission for 5.0.0)
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35

Plunkr Case (Bug Reports)
http://plnkr.co/edit/Ji8fIY5NVx6jaX3StpXI?p=preview

Current behavior
The time picker input box displays 00 in the hours section when 12 hour time is selected.
Additionally, when you type in "12:XX AM" where XX are digits, the picker switches it to PM.

Expected behavior
00 should never displayed in the hour section for 12 hour time. 12 hour time never has a 00 in the hour.

24 hour time: 23:59 -> 00:00
12 hour time: 11:59 PM -> 12:00 AM

Additionally, when you type in "12:XX AM" where XX are digits, the picker should not switch it to PM, and it should instead remain AM.

Minimal reproduction of the problem with instructions
See Plunker
See #4312 for the previous submission of this bug

What is the motivation / use case for changing the behavior?
This behavior is extremely confusing for 12 hour time users, and those not familiar with 24 hour time may be unable to use the picker.

Please tell us about your environment:
VSCode, Windows 10

Angular version: 4.4.3

PrimeNG version: 5.0.0

Browser: All

Language: All

### PR DESCRIPTION
**Pull request by SteveByerly**
###Defect Fixes
Fixes #4486 

###Feature Requests
Due to company policy, we are unable to accept feature request PRs with significant changes as such cases has to be implemented by our team following our own processes.
Smaller scaled feature implementations such as adding a property to a component will be considered for merging.

### CODE REVIEW

**Comment by CNitschelm** [comment]
@SteveByerly @cagataycivici As you can see in #4486, I have confirmed that this pull request fixes the reported bug.

**Comment by cagataycivici** [comment]
+477 −479 changes, impossible for me to understand what the fix is, sorry.

**Comment by cagataycivici** [comment]
Please provide a PR that only adds the fix, nothing more as previous PR does many unrelated changes which made it impossible for us to review what is new.

**Comment by SteveByerly** [comment]
@cagataycivici only using the # of lines that changed is not a good metric for determining if this PR should be reviewed - most of those lines are extraneous whitespace that should not have been in the file to begin with.

I believe if you look at the code in the PR it will not be 'impossible' to understand. Most of the actual code that changed is to fix the logic that created the bug in the first place.

**Comment by SteveByerly** [comment]
@CNitschelm thanks for the time you spent reviewing and troubleshooting. It looks like the fix won't get merged.

**Pull request closed without merging**
