### PR TITLE
#14503 - fix: selecting dropdown option should reset filter

### PR DESCRIPTION
**Pull request by mlz11**
This PR helps solve #14503.

### CODE REVIEW

**Review by SoyDiego — APPROVED** [review]

**Review by SoyDiego — APPROVED** [review]

**Comment by cetincakiroglu** [comment]
Hi,

Could you please resolve the conflicts so we can merge safely?

**Comment by mlz11** [comment]
> Hi,
> 
> Could you please resolve the conflicts so we can merge safely?

Done @cetincakiroglu ✅

**Comment by mlz11** [comment]
@cetincakiroglu little 🆙 😄

**Comment by cetincakiroglu** [comment]
Hi,

Thanks a lot for the effort and support!

Dropdown component has `resetFilterOnHide` input and setting it true resets the filter. Closing the PR since this feature is already exist.

**Pull request closed without merging**
