### PR TITLE
Support keyboard events in multiselect

### PR DESCRIPTION
**Pull request by brachi-wernick**
will solve this issue: https://github.com/primefaces/primeng/issues/3975

### CODE REVIEW

**Comment by cagataycivici** [comment]
Is it possible to fix the end of line character issue, it is not clear which lines are changed from diff.

**Comment by brachi-wernick** [comment]
@cagataycivici try do in the url of github `?w=1`. this should help

**Comment by cagataycivici** [comment]
We'll do it on our side, thank you.

**Comment by Dekel-Cohen** [comment]
@cagataycivici  We saw you removed it from ```4.2.3`` milestone. 
Can you please specify on which version do you think it will get in?

**Pull request closed without merging**
