### PR TITLE
Improve AutoComplete Object support #1580

### PR DESCRIPTION
**Pull request by remmeier**
added possibilitity to specify a pipe as input to the auto-complete component. The pipe allows to transform data values before displaying them in the input control resp. as elements of the dropdown list. This is required in various scenarios like support actual objects as data, formatting of strings, etc.

please check the approach, I will then finalize and test.

### CODE REVIEW

**Comment by odedolive** [comment]
Why use pipes when you can transform the objects using the already supported templates?

**Comment by remmeier** [comment]
itemTemplates only affects the elements in the dropdown. The pipe also adjusts the contents of the input control. This means the autoComplete components becomes enabled to bind to complex objects with ngModel and to format those objects for display in the input control and dropdown. With support for this, it is not necessary to workaround this outside of the autocomplete component.

There is already rudimentary support for this with "field" and resolveFieldData. The pipe, however, is more generic and allows more powerful customizations. Looking at it again, I think the logic for the two should be merged.

**Comment by remmeier** [comment]
I think it is a bit of a more general issue in primeng. With a similar pattern in Calendar you could resolve https://github.com/primefaces/primeng/issues/1810 as well.

**Comment by cagataycivici** [comment]
I'd suggest templating instead for customization. We'll consider input pipe if there is demand in the future.

**Comment by remmeier** [comment]
but the current template does only allow to customize the dropdown???

**Comment by remmeier** [comment]
not the input field

**Comment by aikrez** [comment]
I agree with remmeir. It is currently not possible to format the input which seems like an ootb feature to me.

For my use case I want to use the autocomplete for a list op people. 
Every person has a firstname and lastname so I want to display the firstname and lastname after I select a person.

**Pull request closed without merging**
