### PR TITLE
Add separate templating parameters for source and target lists

### PR DESCRIPTION
**Pull request by thedanielgray**
###Defect Fixes
This adds a feature described in issue #6076, where there are targetItem and sourceItem template types that allow the programmer to separately template items in the source and target list.

### CODE REVIEW

**Comment by cagataycivici** [comment]
We'll do it on our side if more users demand it, thank you.

**Comment by thedanielgray** [comment]
Is there some sort of stylistic/architectural difference that prevents you from merging in the pull request? I put effort into separating all the changes I did into small deltas specific for every feature and to match your coding style as closely as possible.

**Comment by zLAs3R** [comment]
Hi,
i'm also highly interested by this feature !!

**Comment by Naveed1842** [comment]
Hi I am also looking for this feature.We have use case we are showing all the user in sourcelist but when client take some user from list we need to show the dropdown with those in target list.If there are two separate template available it will easy.Will you please add this feature.

**Comment by aammfe** [comment]
Hello!! I m looking for this feature as well..
we have to show all product and user will select those products and in target like he will add quantity to it.
so yes this feature is must.

**Comment by danorr** [comment]
Would very much welcome this feature as I'm needing to show the items that have already been selected by a user in the targetList.
Yes please!

**Comment by johnmarian** [comment]
Would also very much like this feature!

**Comment by francowhyline** [comment]
Hi! We need this feature also!

**Comment by cloggy45** [comment]
And update on this?

**Comment by kralphs** [comment]
Would like this as well

**Comment by danielthegray** [comment]
It's kinda hilarious/sad that even though I did the work for this feature, over 4 years ago, and packaged it in as small a form as possible, as respectful as possible with the existing code styles, it was closed with a simple "not-invented-here" argument of "we'll do it on our side if there is demand", and even after so much demand from people both here and in the issue, no response has been given.

**Comment by BryceSimtars** [comment]
> We'll do it on our side if more users demand it, thank you.

Many people have requested this and @danielthegray provided a very clean and simple implementation, why is it being ignored?

**Pull request closed without merging**
