### PR TITLE
fixed issue #11632 - dynamic dialog multiple instance

### PR DESCRIPTION
**Pull request by shayan-ghzl**
If you try to open the same dialog again, in this case, the method will return null

    const ref = this.dialogService.open(AppComponent, {
      showHeader: false,
    });
    if (ref) {
      ref.onClose.subscribe(() => {

      });
    }

### CODE REVIEW

**Comment by mertsincan** [comment]
Hi @shayan-ghzl,

Thanks a lot for your contribution! But, this PR is outdated. Could you please update it? Then, We'll review it. 

Best Regards,

**Comment by mertsincan** [comment]
Hi,

Unfortunately, there seems to be a lot of conflicts. So a new PR might be better. For now, closed. Could you please create a new PR for us? I'll merge asap. Thanks a lot for your understanding and contribution!

Best Regards,

**Comment by hervehobbes** [comment]
Hello,

I'm using Primeng version 16.5.1, is this bug still present please?

**Comment by hervehobbes** [comment]
I "fixed" the issue by adding this to the dialog configuration :
config.duplicate = true;

**Pull request closed without merging**
