### PR TITLE
In primeng calendar, date can be lined through or disabled using date… there is no way to disable years

### PR DESCRIPTION
**Pull request by faisal6699**
When maxDate or minDate is used, particular date or month gets disabled but there is no way to disable years outside the range of max or min date.

Related issue id: #12151, #12583

### CODE REVIEW

**Comment by ashikjs** [comment]
I also need this feature someone can approved this feature ??

**Comment by ashikjs** [comment]
@cetincakiroglu can you take a look this feature PR ?

**Comment by mertsincan** [comment]
Hi @faisal6699,

Sorry for the delayed response! Unfortunately, this PR is out of date. Could you please update it? I'll merge it asap.

Thanks a lot for your contribution!
Best Regards,

**Comment by faisal6699** [comment]
Hello @mertsincan, 

Thanks for your response. I have resolved the conflict . You can now merge it if everything looks fine to you.

**Comment by mertsincan** [comment]
Thanks a lot for your contribution!

Best Regards,

**Comment by Niseel** [comment]
Hi @mertsincan Now how can I know from which version this error will no longer exist? 
I'm using 
**Angular 14.2.2**
**PrimeNG ~14.1.0**
and still see this error persisting.

**Comment by ashikjs** [comment]
@Niseel this issue resolved in 16.3.0 so you need to upgrade your PrimeNG to 16.3.0

**Comment by Niseel** [comment]
**_Angular 14.2.2_**
**_PrimeNG ~14.1.0_**
Hi @ashikjs Thanks for ur answer. Is there another way to fix this error without changing the version?

**Comment by ashikjs** [comment]
@Niseel Sorry i don't have idea.

**Pull request merged**
