### PR TITLE
Fixes #8647: Ability to remove single toast/message

### LINKED ISSUE #8647: Toast custom template close button
[x ] feature request 

**Current behavior**
I am not able to create my own close button in custom toast because there is no close method i could use.

**Expected behavior**
Add method to message service that removes toast by id or something like that.

* **Angular version:** 8

* **PrimeNG version:** 8.1.1

* **Browser:** all

### PR DESCRIPTION
**Pull request by rg1220**
### Defect Fixes
Fixes https://github.com/primefaces/primeng/issues/8647

### Feature Requests
Adds ability to remove a toast/message via Message reference.

A `remove(message: Message)` function is added to the `MessageService` to enable end users to remove a toast after it has been created. Use case is for having multiple toast messages that are sticky and allowing the application to remove each toast as desired rather than needing to remove all toasts via the `clear()` function.

If there are any issues with the PR, please let me know as my team would be eager to see this merged 😃

### CODE REVIEW

**Comment by rg1220** [comment]
@yigitfindikli - Any chance this could be reviewed and merged in?

**Review by ivava777 — APPROVED** [review]

**Comment by ivava777** [comment]
It would be very helpful to get this feature.
Thanks in advance.

**Comment by ehlisrr19** [comment]
I've run into this a few times, this fix would be very helpful.

**Comment by rg1220** [comment]
Fixed the merge conflict that was in `toast.ts`.

**Comment by rg1220** [comment]
@cagataycivici - Is this something you can review? More than happy to make any necessary changes. Thanks!

**Comment by rg1220** [comment]
@yigitfindikli @cagataycivici - Just bumping this to see if this PR could get considered.

**Review by KYRY001 — APPROVED** [review]

**Comment by mvolponiCF** [comment]
Hey folks,
Is there any chance to have this new feature released? It would be very helpful.

Thanks much!

**Comment by aironhight** [comment]
This will be very useful! :)

**Comment by peterfotinis** [comment]
+1 really need this functionality

**Comment by danni-filipovic** [comment]
Agree with the others, this is much needed

**Comment by mertsincan** [comment]
Hi @rg1220,

Sorry for the delayed response! Could you please update your PR? We'll merge it asap. 

Thank you,
Best Regards,

**Comment by leo-holanda** [comment]
It's great to see this feature being merged. As others have said, it would be very useful. I'm facing a problem right now that this would solve. Thanks for the initiative!

**Comment by rg1220** [comment]
> Hi @rg1220,
> 
> Sorry for the delayed response! Could you please update your PR? We'll merge it asap.
> 
> Thank you, Best Regards,

Sounds good! I'll try and get to it this week.

**Comment by mertsincan** [comment]
Hi @rg1220,

Unfortunately, there seems to be a lot of conflict. So a new PR might be better. For now, closed. Could you please create a new PR for us? I'll merge asap. Thanks a lot for your understanding and contribution!

Best Regards,

**Pull request closed without merging**
