### PR TITLE
[Feature] Custom chips separators

### PR DESCRIPTION
**Pull request by FallenRiteMonk**
Gives the user the possibility to specify which keys are used to separate chips on input.

As the last PR #1628 was closed without giving the possibility to fix, I hope this one is cleaner and will be accepted.

### CODE REVIEW

**Comment by cagataycivici** [comment]
We'll consider and reopen if more users demand it. No significant value added with customizable keys as I've mentioned in previous PR as enter seems the natural choice.

**Comment by BastianR** [comment]
This feature would be perfect. As an option, a separator key could be specified.

**Comment by Franky238** [comment]
Yes, good feature ... and something like action `addChip()` will be better because creating chip by click on button is now impossible

**Comment by nmobregon** [comment]
Dear @cagataycivici , for multiple emails, tab key is also a common choice.
I created issue [3527](https://github.com/primefaces/primeng/issues/3527) asking for this feature. 
Thanks

**Pull request closed without merging**
