### PR TITLE
Issue #9147 - Global locale configuration for calendar component

### PR DESCRIPTION
**Pull request by mrdlink**
Feature Requests - Calendar Component
 
For simplicity, add a `LocaleSettings` object to the `PrimeNGConfig` service to globally set `locale` and `dateFormat` for every `p-calendar` component. The global configuration can be overwritten by setting the `locale` and `dateFormat` attributes of a `p-calendar` component.

### CODE REVIEW

**Comment by mrdlink** [comment]
#9147 will be covered with this PR

**Comment by yntelectual** [comment]
H thanks for this MR, could you, please, fix the merge conflicts so this could be merged? 
@cagataycivici Could you have a look on this if it is otherwise ok? This possibility of global local configuration is a must-have for any larger app as it removes lots of repeated code from componetns. Thanks

**Comment by cagataycivici** [comment]
We've also done it for PrimeNG 11, calendar now uses global is18n config.

**Comment by PHuhn** [comment]
Hey:
This feature would be greatly appreciated for p-table filtering to be consistent with the table date format. I don't seem to find any documentation on setting date format globally.  I also do not see dateFormat in the PrimeNGConfig (I18N) documentation nor do I see it in the API source.
Phil

**Comment by PHuhn** [comment]
Hey:
Your StackBlitz example displays a warning console message of:
Locale property has no effect, use new i18n API instead.

The unit test in the spec not needed.

Please supply an example of using the new i18n API !!!

**Comment by PHuhn** [comment]
I created an example, but it does not seem to support setting dateFormat.

HTML:
```
<h5>Calendar</h5>
<div class="p-fluid p-grid p-formgrid">
  <div class="p-field p-col-12 p-md-4">
    <label for="spanish">Spanish</label>
    <p-calendar [(ngModel)]="es_date" inputId="spanish"></p-calendar>
  </div>
</div>
```
TS:
```
import { Component, OnInit, OnDestroy } from '@angular/core';
import { PrimeNGConfig } from 'primeng/api';
@Component({
  selector: 'app-root',
  templateUrl: './app.component.html'
})
export class AppComponent implements OnInit {
  constructor( private config: PrimeNGConfig ) {}
  es_date: Date;
  ngOnInit() {
    this.config.setTranslation( {
      dayNames: [ "domingo","lunes","martes","miércoles","jueves","viernes","sábado" ],
      dayNamesShort: [ "dom","lun","mar","mié","jue","vie","sáb" ],
      dayNamesMin: [ "D","L","M","X","J","V","S" ],
      monthNames: [ "enero","febrero","marzo","abril","mayo","junio","julio","agosto","septiembre","octubre","noviembre","diciembre" ],
      monthNamesShort: [ "ene","feb","mar","abr","may","jun","jul","ago","sep","oct","nov","dic" ],
      today: 'Hoy',
      clear: 'Borrar',
      weekHeader: 'Sm'
    });
  }
}
```

**Pull request closed without merging**
