### PR TITLE
Fix: #10630

### LINKED ISSUE #10630: Scrolling in a t-table that implements virtual scrolling and lazy loading bugs out the header of the t-table
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://primeng-tablevirtualscroll-demo-6scvvq.stackblitz.io 

**Current behavior**
While scrolling a basic p-table that implements virtual scrolling and lazy loading, it looks like the header doesn't stick to the top of the t-table. I did some investigating myself (in a work-related project) and think this bug is caused by the cdk-virtual-scroll.

The bug really shows itself when scrolling up and down really fast in the part of the t-table where the currently loaded rows collide with the empty (to be loaded by the lazyLoadEvent) rows, I added a screencapture of the stackblitz to make it as clear as possible.

**Expected behavior**
The header of the t-table does not move when scrolling.

**Minimal reproduction of the problem with instructions**
I used the primeNG official demo fork to reproduce this problem, I also added some html/css and inline styling to set the height of the p-table. While running the stackblitz, scroll through the p-table and when you're about to hit a lazyLoadingEvent, start scrolling up and down really fast, the table header should start to move. Even easier to reproduce if you click in the middle of the scrollbar and then, before the records can load, start scrolling up and down really fast. Both cases were recorded in the following screencapture:
wTF3mQN34o

**What is the motivation / use case for changing the behavior?**
If I use the p-table component in my work-project, the behavior becomes much worse, to the degree where I cannot upgrade my project to version 12.1.1.

**Please tell us about your environment:**
OS: Windows 10
Browser: Google Chrome
Can be reproduced in stackblitz, so all other environment information should be accessible there.

* **Angular version:**
Angular version: 12.X

* **PrimeNG version:**
PrimeNG version: 12.1.1

* **Browser:**
Chrome: Version 93.0.4577.82 (Official Build) (64-bit)
 
* **Language:** N/A

* **Node (for AoT issues):** `node --version` =   N/A

### PR DESCRIPTION
**Pull request by Laurent02**
###Defect Fixes
This PR will fix #10630

### CODE REVIEW

**Comment by Laurent02** [comment]
There appeared to be an issue with the table header when virtual scrolling was enabled while scrolling horizontally due to my fix. Fixed that now as well.

**Comment by Laurent02** [comment]
Fixed another issue I encountered with scroll bars. Would really like some feedback on it now because we really need this fix asap @cagataycivici @yigitfindikli  @cetincakiroglu

**Comment by Laurent02** [comment]
I fixed another small issue related to the scrollbar behaviour on the cdk-virtual-scroll-viewport. See attached gif for the behaviour I fixed by adding the padding.

PrimeNG

**Comment by iM4x** [comment]
You kind of reverted the component to its condition before PrimeNg v12.1, nearly the same way I expected the contributors of PrimgNg would do. Keeping the header and footer outside of CdkVirtualScrolling, as PrimeNg also did before in the TableBodyTemplate, is the correct way from my point of view. Your implementation looks good to me, well done :) Hopefully they will merge it soon.

**Comment by cagataycivici** [comment]
We've decided to use our own virtual scrolling that we have in PrimeVue and PrimeReact to resolve this. CDK just doesn't work well for our cases. Target is PrimeNG 14 - Angular 14 likely to be back ported to v13 as well.

**Comment by Laurent02** [comment]
> We've decided to use our own virtual scrolling that we have in PrimeVue and PrimeReact to resolve this. CDK just doesn't work well for our cases. Target is PrimeNG 14 - Angular 14 likely to be back ported to v13 as well.

That's great news, thanks guys. I agree that the main issue is with the CDK virtual scrolling and that this fix was only moving the issue from vertical to horizontal scrolling which made it less disruptive, so effectively no longer using CDK sounds great. Can't wait for the fix to arrive ;)

**Pull request closed without merging**
