### PR TITLE
Custom equality function

### PR DESCRIPTION
**Pull request by meltedspark**
#3149, #3151, #3150

### CODE REVIEW

**Comment by meltedspark** [comment]
@cagataycivici , will it merged?

**Comment by cagataycivici** [comment]
We'll reconsider when more users demand it, currently there is none afaik. thank you.

**Comment by lhoussin** [comment]
As in Angular : https://angular.io/api/forms/SelectControlValueAccessor
a function like compteWith in primeng is needed, hope it will be implemented very soon.

**Comment by PaddingtonTheBear** [comment]
This feature would solve a lot of headaches when dealing with complex objects in dropdowns, multiselect, listbox, etc. 

I want to have my complex objects be the values of my dropdowns, but then comparing the selected item to the dropdown values becomes very specific. If any key of the objects is missing, or different, then the comparison fails (long story short, my dropdown values have more nested properties in them then the actual selected value).

Ideally, I would just do comparisons between the values and the selected using "id", but this is not simple without a custom comparison function. I can have the DataKey defined to use "id," but then this causes the primeng-utils "equals" to be messed up, as the `obj1` is my selected complex object, and then `obj2` is now simply an `id` string which fails the comparison checks done by `this.resolveFieldData` (it doesn't account for comparison an object to a string).

I can try to work around this by transforming the values in my dropdown from complex objects into the `{label, value}` format, but then when I select a value from the dropdown, the selected object is no longer in a format I expect and would have to untransform it. 

Either the `this.resolveFieldData` method needs to be fixed for this use case, or simply extend the functionality by including a `[compareWith]` custom function on all components that need it (similar to how core Angular and other UI libraries do it).

**Pull request closed without merging**
