### PR TITLE
Add appendTo to Dynamic Dialog

### PR DESCRIPTION
**Pull request by shayl29**
#9546

### CODE REVIEW

**Comment by shayl29** [comment]
Solves https://github.com/primefaces/primeng/issues/9546

**Comment by mertsincan** [comment]
Hi @shayl29,

Sorry for the delayed response! Could you please update your PR? Then, I'll merge it asap.

Best Regards,

**Comment by shayl29** [comment]
> Hi @shayl29,
> 
> Sorry for the delayed response! Could you please update your PR? Then, I'll merge it asap.
> 
> Best Regards,

Hey, sure I'll get to it later today

**Comment by shayl29** [comment]
Hey @mertsincan merged the changes.
Took me some time to find out where the docs went. Also cool vercel thingy 💪

**Comment by mertsincan** [comment]
Thanks a lot for your contribution!

**Pull request merged**
