### PR TITLE
dynamic dialog: making auto focus on first button optional

### PR DESCRIPTION
**Pull request by inikel**
### Defect Fixes
When submitting a PR, please also <ins>**create an issue**</ins> documenting the error and [manually link to an issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#manually-linking-a-pull-request-or-branch-to-an-issue-using-the-issue-sidebar) or mention it in the description using #<issue_id>.

### Feature Requests
Due to company policy, we are unable to accept feature request PRs with significant changes as such cases has to be implemented by our team following our own processes.
Smaller scaled feature implementations such as adding a property to a component will be considered for merging.

### CODE REVIEW

**Comment by inikel** [comment]
this PR is related to issue https://github.com/primefaces/primeng/issues/13486

**Review by SoyDiego — APPROVED** [review]

**Comment by SoyDiego** [comment]
Your code it's ok but I don't know If they will approve this because If I understand OK, for Accessibility is mandatory the autofocus.

**Comment by inikel** [comment]
> Your code it's ok but I don't know If they will approve this because If I understand OK, for Accessibility is mandatory the autofocus.

@SoyDiego good point
I have changed logic a bit, so autofocus now is enabled by default as it was

**Comment by chris-tremblay** [comment]
Is this going to be merged?

**Pull request closed without merging**
