### PR TITLE
refactor(): switch to new HttpClient

### PR DESCRIPTION
**Pull request by danielsogl**
Just a small change switching to the new Angular HttpClient introduced with Angular 4.3.

### CODE REVIEW

**Comment by cagataycivici** [comment]
Doesn't this break apps of Angular 4.2 users?

**Comment by danielsogl** [comment]
It should only affect the PrimeNG Website.

**Comment by cagataycivici** [comment]
Oh, I see now, ok, will add after 4.2.0 is out this week. Thank you.

**Comment by cagataycivici** [comment]
Merged manually, thank you.

**Pull request closed without merging**
