### PR TITLE
Fixed primefaces#16576 - Column Filter missing primary color

### PR DESCRIPTION
**Pull request by EnricoMessall**
fix: primefaces#16576

+ CX Function add support for flatting functions for styleClass (Similar to ngStyle doing it)
+ Added new theming for p-column filter active button color
+ Added p-datatable-column-filter-button-active class again

The cx function adjustment is important so parts using [styleClass] can work with cx having a function as return value. With that the cx functions flattens the function result as the ngStyle does and directly provides styleClass with the required string. Making styleClass do that directly would require a rework of all styleClass components so that was the best option from my point of view.

### CODE REVIEW

**Comment by rosenthalj** [comment]
This PR #16588 doesn't fix Issue #16576.

I download the PR branch and tested the fix.  The video and annotate3d screenshot listed below shows that this PR doesn't fix Issue #16576:  **"When a table column is filtered using the p-columnFilter component there is no indication of filtering in the corresponding table column header"**.


https://github.com/user-attachments/assets/6d74bb8e-0837-4ca7-aade-d45b023b4ce7



Angular_Table_Component

**Comment by EnricoMessall** [comment]
@rosenthalj Look at the video i send, i couldnt upload it here because its too big for github. Its also showing this MR, you can see how the active button is applied to the filter but the color is new in PrimeNG v18 and is also black but with another level of darkness. You can also see that i change the overall primary color token and then also the selected filter color changes to the adjusted primary color.

**Comment by rosenthalj** [comment]
> @rosenthalj Look at the video i send, i couldnt upload it here because its too big for github. Its also showing this MR, you can see how the active button is applied to the filter but the color is new in PrimeNG v18 and is also black but with another level of darkness. You can also see that i change the overall primary color token and then also the selected filter color changes to the adjusted primary color.

@EnricoMessall  can you try saving your video at a lower resolution or provide screenshots? I can not verify the results of your PR.  Somehow/Somewhere something is obviously wrong or inconsistent?

**Comment by EnricoMessall** [comment]
@rosenthalj Look into the primeng discord. I've messaged you there with the video.

**Comment by rosenthalj** [comment]
@EnricoMessall 

Your video on **PrimeNG Discord** is nice and I now understand what you are trying to convey.

I confirmed that after your changes, the **p-datatable-column-filter-button-active** class is now being added to the filter button.  This is similar to v17.  PrimeNG v17 uses the **p-column-filter-menu-button-active** class for the filter button.  It appears that PrimeNG v18 is changing a lot of CSS class names.

Unfortunately,  even with your changes,  the PrimeNG Table Filter Advance Demo is still not working properly.  As a result,  any software upgraded from 17.x  to 18.x will still not have any visual indication when the  table has been filtered unless the developer realizes its now their responsibility to fix table filter visual indicators.


Note on your video: You were eventually able to change the filter button color by using the browser's "inspection" functionality.   In v17 both the filter button color and the filter button background colors are changed to indicate  a column has been filtered.

**Comment by EnricoMessall** [comment]
Hi @mertsincan i've fixed Merge Conflicts. I would please you to not take that long with merging it due to the size of changes, i acutally dont want to resolve all conflicts in every file a fourth time :D

**Comment by mertsincan** [comment]
Thanks a lot for your contribution! But, unfortunately, we cannot accept this PR. New tokens can only be added by the PrimeNG team. Because we have many products related to it and we have to make decisions with the design team to add new tokens.

**Pull request closed without merging**
