### PR TITLE
Calendar

### PR DESCRIPTION
**Pull request by martine-dowden**
Issue: Calendar Accessibility #2386

### CODE REVIEW

**Comment by SIlver--** [comment]
I hope this pull gets accepted. Very annoying for it not to be accessible(although the fault lies on fullcalendar)

**Comment by cagataycivici** [comment]
Please update the PR due to conflict.

**Comment by martine-dowden** [comment]
Comments state above that you want me to update the pull request, yet it is closed. Did you want me to go ahead and create a new one?

**Comment by neeraj07rathi** [comment]
Can somebody please merge this change.

**Pull request closed without merging**
