### PR TITLE
Fix #14010, #13162, #13768, #13082, #10472

### LINKED ISSUE #10472: In a Dynamic Dialog that is opened from another Dynamic Dialog, we can not press Tab to focus on the next field
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Stackblitz Case (Bug Reports)**
https://stackblitz.com/edit/primeng-dynamicdialog-demo-adhpi8

**Current behavior**
1. Open a Dynamic Dialog from another Dynamic Dialog.
2. There are some input fields in the dialog, when I press Tab, it will not focus on the next field.

You can try the issue by the link Stackblitz above.

**Expected behavior**
It should focus on the next input field.

**What is the motivation / use case for changing the behavior?**
If the dialog I mentioned is the dialog of filling some fields, the tab-focus-next-field behavior should works.

**Please tell us about your environment:** Stackblitz

* **Angular version:** 11.0

* **PrimeNG version:** 11.3.0

* **Browser:** I tested on Chrome and Firefox
 
* **Language:** TypeScript

### LINKED ISSUE #13082: Autofocus
### Describe the bug

Hello! I am using your library. And I have one problem when I use your DynamicPopupComponent and inside it I have an input with your directives pInputText pAutofocus [autofocus]=true. After popup opened, focus leave input element and set to "x" button in top-right corner. This is not very convenient, have to come up with own implementation : like write own ngAfterContentChecked() and set forcibly focus on your pInputText element.

### Environment

Local

### Reproducer

_No response_

### Angular version

15

### PrimeNG version

15.4.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.16.0

### Browser(s)

_No response_

### Steps to reproduce the behavior

_No response_

### Expected behavior

_No response_

### LINKED ISSUE #13162: Component: Dynamic Dialog's Autofocus on Close Button
### Describe the bug

In previous versions, the dynamic dialog did not affect the initial autofocus. However, it focus to the Close button automatically

### Environment

No specific environment.

### Reproducer

_No response_

### Angular version

16.0.3

### PrimeNG version

v16.0.0-rc.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

v18.16.0

### Browser(s)

_No response_

### Steps to reproduce the behavior

1. Open a dialog with `closable: true` like this:
```typescript
this.dialogService.open(ExampleDialogComponent, {
    header: 'Dialog header',
    closable: false
});
```
2. View the result

Screenshot from 2023-06-08 09-03-39

### Expected behavior

Should be 1 of these solutions:
- Do not allow to autofocus the close button.
- Add new property named `isCloseButtonAutofocus` or something like that to make sure that we can turn on/off the autofoccus for the close button.

### LINKED ISSUE #13768: DynamicDialog: Add support for focusOnShow (like Dialog component)
### Describe the feature you would like to see added

Add the possibilty to disable auto focus when DynamicDialog open with configuration. 

### Is your feature request related to a problem?

Some times i only have one button on my modal ( for example : close cross ) and the focus is automaticly set to it and it create focus css style to be triggered and look and feel is not good. 

### Describe the solution you'd like

Add a property to DynamicDialog configuration.
Like for Dialog component we can use focusOnShow property (default true). 

### Describe alternatives you have considered

I tried different workaround to disable the focus: 

- Hidding it with css
- Creating a hidden button to catch the focus
- Replacing the button with an anchor

But none of this solutions look clean to me. It would be better if we can disable this behaviour with a simple property. 

### Additional context

_No response_

### LINKED ISSUE #14010: AutoFocus for Dropdown: Does not work inside dialogComponent.
### Describe the bug

If AutoFocus is used for Dropdown inside a dialog, focus is not applied to the element.

For Text Box AutoFocus is working fine.
If Dropdown is not in dialog - AutoFocus is working fine.

### Environment

Any Environment.

### Reproducer

_No response_

### Angular version

16.2.11

### PrimeNG version

16.7.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

14.9.3

### Browser(s)

Chrome 90

### Steps to reproduce the behavior

1. Add p-dropdown inside p-dialog
2. Set [autofocus]=true to p-dropdown
3. Focus is not on dropdown.

### Expected behavior

Focus should be on p-dropdown

### PR DESCRIPTION
**Pull request by BGBRWR**
fix #14010, fix #13162, fix #13768, fix #13082, fix #10472

### CODE REVIEW

**Comment by cetincakiroglu** [comment]
Hi @BGBRWR 

Thanks for fixing all these issues, we appreciate the effort and support!

**Comment by leykee** [comment]
@cetincakiroglu @BGBRWR this PR introduced some unexpected behaviour. Now anything focusable inside the dialog gets focus, for instance I have a form inside a modal, where the first focusable element is a p-calendar, this opens the calendar overlay immediately, but we don't want that, because it covers other form elements. 

Wether to focus the first focusable element within a dialog should be configurable with an option.

**Comment by dodesheide** [comment]
After this issue i run to errors with Dialog and headless mode:

https://github.com/primefaces/primeng/issues/15496

**Comment by BGBRWR** [comment]
> @cetincakiroglu @BGBRWR this PR introduced some unexpected behaviour. Now anything focusable inside the dialog gets focus, for instance I have a form inside a modal, where the first focusable element is a p-calendar, this opens the calendar overlay immediately, but we don't want that, because it covers other form elements.
> 
> Wether to focus the first focusable element within a dialog should be configurable with an option.

You can set `focusOnShow` on the dialog to `false`.

**Comment by leykee** [comment]
> > @cetincakiroglu @BGBRWR this PR introduced some unexpected behaviour. Now anything focusable inside the dialog gets focus, for instance I have a form inside a modal, where the first focusable element is a p-calendar, this opens the calendar overlay immediately, but we don't want that, because it covers other form elements.
> > Wether to focus the first focusable element within a dialog should be configurable with an option.
> 
> You can set `focusOnShow` on the dialog to `false`.

Tried that, doesn't work. Your code seems to ignore the flag

**Comment by rbbp23** [comment]
Another issue introduced by this PR.
On a dynamic dialog with a custom header and a footer template, I get a kind of infinite focus with the following error:

core.mjs:6531 ERROR RangeError: Maximum call stack size exceeded
    at DomHandler.getFocusableElement (primeng-dom.mjs:553:31)
    at DynamicDialogComponent.focus (primeng-dynamicdialog.mjs:592:36)
    at DynamicDialogComponent.focus (primeng-dynamicdialog.mjs:607:18)
    at DynamicDialogComponent.focus (primeng-dynamicdialog.mjs:607:18)
    at DynamicDialogComponent.focus (primeng-dynamicdialog.mjs:607:18)
    at DynamicDialogComponent.focus (primeng-dynamicdialog.mjs:607:18)
    at DynamicDialogComponent.focus (primeng-dynamicdialog.mjs:607:18)
    at DynamicDialogComponent.focus (primeng-dynamicdialog.mjs:607:18)
    at DynamicDialogComponent.focus (primeng-dynamicdialog.mjs:607:18)
    at DynamicDialogComponent.focus (primeng-dynamicdialog.mjs:607:18)

**Comment by TheWrightDev** [comment]
@rbbp23 Have you found any solution to this? This error completely breaks our ui ordering when it occurs, something weird happens with the z-index and things start appearing underneath random components on the page.

**Comment by BGBRWR** [comment]
> > > @cetincakiroglu @BGBRWR this PR introduced some unexpected behaviour. Now anything focusable inside the dialog gets focus, for instance I have a form inside a modal, where the first focusable element is a p-calendar, this opens the calendar overlay immediately, but we don't want that, because it covers other form elements.
> > > Wether to focus the first focusable element within a dialog should be configurable with an option.
> > 
> > 
> > You can set `focusOnShow` on the dialog to `false`.
> 
> Tried that, doesn't work. Your code seems to ignore the flag



> > > @cetincakiroglu @BGBRWR this PR introduced some unexpected behaviour. Now anything focusable inside the dialog gets focus, for instance I have a form inside a modal, where the first focusable element is a p-calendar, this opens the calendar overlay immediately, but we don't want that, because it covers other form elements.
> > > Wether to focus the first focusable element within a dialog should be configurable with an option.
> > 
> > 
> > You can set `focusOnShow` on the dialog to `false`.
> 
> Tried that, doesn't work. Your code seems to ignore the flag

If you could create an issue with a stackblitz reproducing the bug because I'm not able to reproduce it myself.

**Comment by BGBRWR** [comment]
> Another issue introduced by this PR. On a dynamic dialog with a custom header and a footer template, I get a kind of infinite focus with the following error:
> 
> core.mjs:6531 ERROR RangeError: Maximum call stack size exceeded at DomHandler.getFocusableElement (primeng-dom.mjs:553:31) at DynamicDialogComponent.focus (primeng-dynamicdialog.mjs:592:36) at DynamicDialogComponent.focus (primeng-dynamicdialog.mjs:607:18) at DynamicDialogComponent.focus (primeng-dynamicdialog.mjs:607:18) at DynamicDialogComponent.focus (primeng-dynamicdialog.mjs:607:18) at DynamicDialogComponent.focus (primeng-dynamicdialog.mjs:607:18) at DynamicDialogComponent.focus (primeng-dynamicdialog.mjs:607:18) at DynamicDialogComponent.focus (primeng-dynamicdialog.mjs:607:18) at DynamicDialogComponent.focus (primeng-dynamicdialog.mjs:607:18) at DynamicDialogComponent.focus (primeng-dynamicdialog.mjs:607:18)



> Another issue introduced by this PR. On a dynamic dialog with a custom header and a footer template, I get a kind of infinite focus with the following error:
> 
> core.mjs:6531 ERROR RangeError: Maximum call stack size exceeded at DomHandler.getFocusableElement (primeng-dom.mjs:553:31) at DynamicDialogComponent.focus (primeng-dynamicdialog.mjs:592:36) at DynamicDialogComponent.focus (primeng-dynamicdialog.mjs:607:18) at DynamicDialogComponent.focus (primeng-dynamicdialog.mjs:607:18) at DynamicDialogComponent.focus (primeng-dynamicdialog.mjs:607:18) at DynamicDialogComponent.focus (primeng-dynamicdialog.mjs:607:18) at DynamicDialogComponent.focus (primeng-dynamicdialog.mjs:607:18) at DynamicDialogComponent.focus (primeng-dynamicdialog.mjs:607:18) at DynamicDialogComponent.focus (primeng-dynamicdialog.mjs:607:18) at DynamicDialogComponent.focus (primeng-dynamicdialog.mjs:607:18)

You should create an issue with a stackblitz reproducing the bug because I'm not able to reproduce it myself.

**Pull request merged**
