### PR TITLE
Fixed #9870: Dropdown toLocaleLowerCase is not a function when optionLabel is a number

### LINKED ISSUE #9870: Dropdown toLocaleLowerCase is not a function when optionLabel is a number
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report
```

I will not put a plunkr because it is something simple.

**Current behavior**

The `optionLabel` of the dropdown expects the value to be a string and calls the function `toLocaleLowerCase`.
However, if the optionLabel represents a number, it will throw an exception `TypeError: this.getOptionLabel(...).toLocaleLowerCase is not a function`

Example at line 966, but there are other lines with the same call.
https://github.com/primefaces/primeng/blob/c9946d3e3cff773b05c642b12b19a0631a5e1408/src/app/components/dropdown/dropdown.ts#L966

**Expected behavior**

I think it would be better to accept numbers as well or at least not throw this hard to understand exception.

### PR DESCRIPTION
**Pull request by GavinWu1991**
###Defect Fixes
[#9870], committing changes to fix numeric optional label searching throw exeception issue

###Feature Requests
Due to company policy, we are unable to accept feature request PRs with significant changes as such cases has to be implemented by our team following our own processes.

### CODE REVIEW

**Comment by bjansen** [comment]
The problem is still present, could someone please reopen this PR?

**Comment by timoerlemans** [comment]
@cagataycivici @cetincakiroglu This problem is still present, could you please reopen this PR?

**Comment by cetincakiroglu** [comment]
Hi, 

Could you please resolve conflicts?

**Comment by mertsincan** [comment]
Hi @GavinWu1991,

Sorry for the delayed response! Unfortunately, we made a lot of changes in Dropdown component and your PR is out of date. So, closed. Could you please create a new PR for us? I'll merge it asap.

Thanks a lot for your understanding!
Best Regards,

**Pull request closed without merging**
