### PR TITLE
Use ngDoCheck to implement the filled property. Fixes #2384, #2379 an…

### LINKED ISSUE #2384: dt.filter() method in dataTable causes ExpressionChangedAfterItHasBeenCheckedError
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**

Use filter method of DataTable (called by event) like this:
`this.dt.filter(filter, column, 'contains');`

Error:
ERROR Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: ''. Current value: '3'.
    at viewDebugError (core.es5.js:8661) [angular]
    at expressionChangedAfterItHasBeenCheckedError (core.es5.js:8639) [angular]
    at checkBindingNoChanges (core.es5.js:8803) [angular]
    at checkNoChangesNodeInline (core.es5.js:12240) [angular]
    at checkNoChangesNode (core.es5.js:12202) [angular]
    at debugCheckNoChangesNode (core.es5.js:12776) [angular]
    at debugCheckRenderNodeFn (core.es5.js:12716) [angular]
    at Object.eval [as updateRenderer] (ColumnHeaders.html:14) [angular]
    at Object.debugUpdateRenderer [as updateRenderer] (core.es5.js:12698) [angular]
    at checkNoChangesView (core.es5.js:12062) [angular]
    at callViewAction (core.es5.js:12381) [angular]
    at execEmbeddedViewsAction (core.es5.js:12359) [angular]
    at checkNoChangesView (core.es5.js:12061) [angular]
    at callViewAction (core.es5.js:12381) [angular]

* **Angular version:** 4.0.0

* **PrimeNG version:** 4.0.0

* **Browser:** [all]

### PR DESCRIPTION
**Pull request by akorchev**
…d #2307.

PrimeNG directives fail due to [this Angular 4 regression](https://github.com/angular/angular/issues/15464). This pull request avoids the problem by using `ngDoCheck` which I also believe is a better way to implement the `filled` feature.

### CODE REVIEW

**Comment by cagataycivici** [comment]
Commented on each issue to discuss.

**Comment by cagataycivici** [comment]
I've tried ngDoCheck but it fails when there is no ngModel;

```ts
export class InputText implements DoCheck {

    constructor(public el: ElementRef) {}
        
    filled: boolean;
        
    ngDoCheck() {
        this.filled = this.el.nativeElement.value&&this.el.nativeElement.value.length;
    }
}
```

```xml
<input id="in" type="text" size="30" pInputText /> 
```

**Comment by akorchev** [comment]
This demo seems to work for me (Chrome and desktop Safari): https://plnkr.co/edit/pHI0BtXHsmbEj97qdnPY?p=preview. Both textareas work - the one with ngModel and the one without. Typing in the empty sets the ui-state-filled and deleting removes it. Does this one work for you?

**Comment by akorchev** [comment]
Also this is a demo which fails immediately when I test in Chrome and desktop Safari: https://plnkr.co/edit/wKUETJ?p=preview

**Comment by cagataycivici** [comment]
Ok, replicated finally. Thank you, let's resolve this today.

**Comment by cagataycivici** [comment]
Weird, I see issue at plunkr but not locally with same versions. I'll merge the changes despite this as I remember having these issues with Angular 4.RC versions.

**Comment by cagataycivici** [comment]
Will merge manually due to end of line character difference.

**Comment by akorchev** [comment]
Sorry about that :(

**Comment by cagataycivici** [comment]
No problem, all should be good now for RC2.

**Comment by ahelord** [comment]
already solved. Uninstall (1.1.4 )and install (4.0.1)Primeng

**Pull request closed without merging**
