### PR TITLE
#5694 Fix the onBeforeToggle bug firing the event before the animation

### PR DESCRIPTION
**Pull request by rafa-as**
#5694

* Fix the onBeforeToggle bug firing the event before the animation
* Add the exposed event collapsedChange to the documentation
* Add attribute to be able to toggle the panel through the header
* A lot of TSLint changes of spaces

### CODE REVIEW

**Comment by rashnk** [comment]
how can I use this code? is pull approved?

**Comment by rafa-as** [comment]
Conflicts resolved

**Comment by cagataycivici** [comment]
So many lines changed as a result I cannot review what the PR does unfortunately. Also the PR does a lot than it should, one PR to change 4 things is too much, each one should be a different PR.

**Comment by rafa-as** [comment]
Thanks @cagataycivici

**Pull request closed without merging**
