### PR TITLE
Fixes issue #8096

### PR DESCRIPTION
**Pull request by francovegini**
### Defect Fixes
Issue #8096

### CODE REVIEW

**Comment by yigitfindikli** [comment]
Thanks for contributing.
Best Regards.

**Comment by lazovic6** [comment]
I think I have a solution for autocomplete, since it still doesn't work. As of 2018, you have to change autocomplete="new-password" instead of autocomplete="off" for it to work (autocomplete="off" doesn't work any more). Checked it, changed it in my project and it works. Hope you will fix this soon

**Comment by francovegini** [comment]
@lazovic6 you can set this value in @Input autocomplete :)

**Comment by lazovic6** [comment]
Just to be clear, i have to set it up like this 
<p-autoComplete [autocomplete]="new-password"></p-autoComplete>  ?? Because I tried this on 8.0.3 primeng and it didnt work, what am I missing?

**Comment by francovegini** [comment]
Yes, just that.

image

image

**Pull request merged**
