### PR TITLE
Added input property compareField for comparing property between valu…

### PR DESCRIPTION
**Pull request by petrbalat**
…es in multiselect

### CODE REVIEW

**Comment by cagataycivici** [comment]
What problem does this solve?

**Comment by petrbalat** [comment]
If you have value as object in SelectItem then compare with operator == is a problem because objects in options can be different instance but with the same values. With this commit you can compare by id for example.

**Comment by petrbalat** [comment]
select2 has a id property for this func. So maybe it will be better rename the property compareField

**Comment by cagataycivici** [comment]
What is the case where you have to compare different select item instances.

**Comment by petrbalat** [comment]
If you have different api which load options e.g. we have components for clients e.g. <clients-select> which always loads all record from /api/clients ... but in other edit form e.g. <edit-bill> clients is property from some dto object. Like I said select2 has id property, kendo has valueField http://www.telerik.com/kendo-angular-ui/components/dropdowns/api/DropDownListComponent/#valuefield-string  ...

**Comment by cagataycivici** [comment]
I see but we need more details, we should not add it just because other libs have it. When you load the options, you bind them to the multi select. When you load them again to change them, same instances are bound as well. Can you post some code where you need compareField? It is not clear.

**Comment by petrbalat** [comment]
e.g. you have a cmp
@Component({
    selector: 'multiselect-clients-cmp',
    template: `
<p-multiSelect [options]="allClients | toSelectItem:'name'" [ngModel]="clients" compareField="id"
defaultLabel="" (onChange)="valueChange($event.value)"></p-multiSelect>
`
})
export class MultiSelectClientsCmp extends AbstractCmp implements OnInit {

    @Input('clients')
    clients:any[] = [];
    @Output('clientsChange')
    clientsChange = new EventEmitter<Array<any>>();

    allClients:any[] = [];

    constructor(http:Http, notificationService:NotificationService) {
        super(http, notificationService, null, null);
    }

    ngOnInit() {
        //clienti do comboboxu
        this.http.get(`/api/admin/clients`).map(res => res.json()).subscribe((res:Array<any>) => {
            this.allClients = res;
        });
    }

    valueChange(items:Array<any>) {
        this.clientsChange.emit(items);
    }
}


but in other cmp

<form>
            <div class="form-group">
                <label>label...</label>
                <multiselect-clients-cmp [(clients)]="dto.clients"></multiselect-clients-cmp>
            </div>
</form>

//delay because of bug  #725  .. https://github.com/primefaces/primeng/issues/725
this.http.get(`/api/admin/user/${this.userId}`).map(res => res.json()).delay(200).subscribe((res:any) => {
            this.dto = res; // clients in dto are diferent instance...but with the same values and unique id
});

**Comment by stephanecot** [comment]
I need the same thing, but maybe I have a better exemple:

This Multiselect has a problem when used in a form in 'modification'.
I have a get request to populate the [**options**] property and then I populate **myForm** ==> this.**myForm**.setValue(**data**). (**data** is another get request)
[**options**] is a list of object: {id: xxx, label: yyy} and my form has a property **zzz** whitch is a list of the same object (but not not the same instance!)

The problem is that the objects in **options** field can't be matched with the list of objects  of **myForm.zzz**. It's not the same instance. They re not way to indicate it's the same object (no method equals() like in java :) ).

**Comment by cagataycivici** [comment]
This PR has too many unrelated commit, please create a issue ticket so we can discuss first.

**Pull request closed without merging**
