### PR TITLE
Feature/add input number attribute transform fns

### PR DESCRIPTION
**Pull request by LcsGa**
This PR as the same background as [this one](https://github.com/primefaces/primeng/pull/14645)

### CODE REVIEW

**Review by cetincakiroglu — APPROVED** [review]

**Comment by cetincakiroglu** [comment]
Hi,

Huge thanks for the effort and support, great PR! 
Could you please resolve the conflicts so we can merge safely?

**Comment by LcsGa** [comment]
Hi! Yes I can resolve the conflicts in 2-3 days and about the 2 PRs, I created this one based on the first one as I thought I could merge this one into thé other and the other one into master 😅
So the other one can be deleted

**Comment by cetincakiroglu** [comment]
@LcsGa ,

Thanks a lot, please tag me after you are done with the changes.

**Comment by LcsGa** [comment]
Hey @cetincakiroglu,
It should be alright now 😉 !

> Sorry for the delay, I had less time than I thought 😅

**Pull request merged**
