### PR TITLE
Pass autocomplete attribute into input element

### PR DESCRIPTION
**Pull request by Salamek**
Pass autocomplete argument to password input, this allows to specify autocomplete behavior like `new-password` to prevent browser from filling in current login info and so on...

Issue #12362

### CODE REVIEW

**Review by pierrefaidherbe — APPROVED** [review]

**Comment by Salamek** [comment]
@pierrefaidherbe hi, i have resolved the conflict in PR...

**Comment by t4keo** [comment]
https://github.com/primefaces/primeng/issues/12362

**Comment by ShukinDmitriy** [comment]
Hey! Is it planned to add this PR in the next versions? I also need this functionality.

**Comment by Salamek** [comment]
Still relevant since Issue https://github.com/primefaces/primeng/issues/12362 is not closed

**Comment by mertsincan** [comment]
Hi @Salamek,

Sorry for the delayed response! Unfortunately, your PR is out of date. Could you please update it with a doc? I will merge it as soon as possible. Thanks a lot for your contribution!

Best Regards,

**Comment by Salamek** [comment]
@mertsincan hi, conflict should be resolved.

**Comment by mertsincan** [comment]
Thanks a lot for your contribution!

**Pull request merged**
