### PR TITLE
fix #8019 

### LINKED ISSUE #8019: Calendar showTime/timeOnly issue - Need to fix [increment/decrement]Minute() methods when minutes hit end of range
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://rlmiyral.github.stackblitz.io

**Current behavior**

Increment 1 minute from 10:59 gives 10:00
Decrement 1 minute from 11:00 gives 11:59

**Expected behavior**

Expect the result of 10:59 + 1 min to be 11:00, not 10:00
Expect the result of 11:00 - 1 min to be 10:59, not 11:59

**Minimal reproduction of the problem with instructions**

import { Component } from '@angular/core';
@Component({
  selector: 'app-root',
  template: '
<h2>PrimeNG Calendar Time Issue</h2>
<p>Increment minute from 10:59. One would expect the result to be 11:00, but PrimeNG goes to 10:00</p>
<p>Decrement minute from 11:00. One would expect the result to be 10:59, but PrimeNG goes to 11:59</p>
<h3>Time Only </h3>
<p-calendar [(ngModel)]="time" [timeOnly]="true"></p-calendar>
'
})
export class AppComponent {
  time = new Date(Date.parse('2019-08-04T15:00:00.000Z'));
}

**What is the motivation / use case for changing the behavior?**
Need Time-Only input with behavior that makes sense

Providing the below info as requested although it's mostly irrelevant [except PrimeNG version]
--------------------------------------------------------------------------------------------------------
**Please tell us about your environment:**

Windows-10
npm - 5.6.0
tomcat - 7

* **Angular version:** 7.2.12

The issue is with PrimeNG logic, has nothing to do with Angular version

* **PrimeNG version:** 7.1.0

It's the same issue in primeNG demo - https://www.primefaces.org/primeng/#/calendar

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

I use Chrome, but  it could be any
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5] 3.1.6

* **Node (for AoT issues):** `node --version` =   v8.11.4

### PR DESCRIPTION
**Pull request by topce**
Fix #8019 
now when increment/decrement minutes , hour is incremented or decremented if needed

same for hours and days
for example 12/31/2024 23:59
if you increase minutes by one you got
01/01/2025 00:00
before you get 12/31/2024 23:00

### CODE REVIEW

**Comment by topce** [comment]
before click
image

**Comment by topce** [comment]
after click to increment minutes
image

**Comment by cetincakiroglu** [comment]
Hi,

Thanks a lot for the effort and support, this behavior is made by design and we don't have any plans to change it. When the time hits 23:59, it should be 23:00 when incremented. Date should stay the same. Closing the PR.

**Comment by topce** [comment]
> Hi,
> 
> Thanks a lot for the effort and support, this behavior is made by design and we don't have any plans to change it. When the time hits 23:59, it should be 23:00 when incremented. Date should stay the same. Closing the PR.
Hi @cetincakiroglu 
No  problem , thank you for great library!

Short explanation : 

I am working on one project that use primeng 
and  testers reported this issues as a bug.
Then I found bug #8019 reported by @krasnymark and there it was labeled like "can't replicate"
and not as "work as intended"

So I decided to contribute to project that I use for free for so many years.
I fix it and create PR and also deploy my fork to npm https://www.npmjs.com/package/@topce/primeng.
and switch project to use my fork until PR is accepted. 

I will transfer  your response (not a bug , work as intended) to our project manager and check with him 
should we go back to main distribution 
(what I would prefer because I do not want to sync and republish  primeng every time you do it) 
or stay on fork, if we prefer to fix this issue and not carry so much for recent updates because primeng is very stable,
and we do not use so many controls.

Thank you for your help and clarifications!

**Pull request closed without merging**
