### PR TITLE
Inputmask autoclear bug fix

### PR DESCRIPTION
**Pull request by odedolive**
When setting the autoClear value to "false" we want to preserve the value entered by the user.

### CODE REVIEW

**Comment by cagataycivici** [comment]
Had to revert because it broke the functionality where on blur incomplete value is cleared.

**Comment by odedolive** [comment]
I'm probably missing something then.
We want the value to stay in the textbox if the mask is incomplete, so that we can give our users the opportunity to fix it (instead of having to re-type it).
Sometimes people forget to enter one or two characters, we don't want them to have to re-enter it all when they tab out accidentally.

**Comment by Whipgit** [comment]
Am I correct in the following:
Setting autoClear="false" or autoClear="true" makes no difference?

**Comment by cagataycivici** [comment]
Angular syntax kinda requires [autoClear]="false" to actually set false if default value of the property is true. Otherwise it sets autoClear as string "false" not boolean false.

**Comment by Whipgit** [comment]
Thank you very much @cagataycivici

**Pull request merged**
