### PR TITLE
#5280 #5288 #5286 #5285 Fix DropwDown clear button

### PR DESCRIPTION
**Pull request by rafa-as**
Include fixes to:
#5280 
#5288
#5286
#5285 

- Prevent the clear button event propagation and removed the condition inside onMouseClick
- Emit onChange event when clear button is clicked
- Added clearButton parameter to show/hide the clear button
- A lot of spaces that WebStorm removes following TSLint.

### CODE REVIEW

**Comment by blackholegalaxy** [comment]
This need to be merged ASAP to prevent dropdown break.

**Comment by rafa-as** [comment]
PR updated

**Comment by jayordway** [comment]
When will this be merged?

**Comment by blackholegalaxy** [comment]
@cagataycivici @Merve7 the clea fixes PR should be merged asap as "emergency patch" after 5.2.1 regressions.

**Comment by cagataycivici** [comment]
All fixed separately already before seeing this, thanks for the PR though.

**Pull request closed without merging**
