### PR TITLE
Add ellipsis feature to data cell in DataTable

### PR DESCRIPTION
**Pull request by davidkirolos**
###Feature Requests
Demo can be found here : [https://davidkirolos.github.io/primeng/#/datatable/colresize](https://davidkirolos.github.io/primeng/#/datatable/colresize)

- Add ellipsis feature to cell data when text is too long, and show tooltip with the rest of the text when mouse hover the cell.
- Add ellipse:boolean attribute to datatable to control this feature, default value is false.

image

image

### CODE REVIEW

**Comment by rachelbr** [comment]
Thanks
good job, helped me

**Comment by cagataycivici** [comment]
Will be reviewed for 5.0.2, thank you.

**Comment by cagataycivici** [comment]
DataTable is deprecated in favor of new p-table so not maintained anymore. You can apply this solution easily on p-table as you have full control over the presentation.

**Comment by ctrl-brk** [comment]
Is there any example how to do it?

**Comment by davidkirolos** [comment]
@ctrl-brk I'll be implementing this on p-table soon.

**Pull request closed without merging**
