### PR TITLE
Fixed lint issues, Modified lint rules, Added Travis lint check

### PR DESCRIPTION
**Pull request by artemnih**
This PR fixes nearly 25000 existing lint issues without modifying the logic or unit tests.
- tslint rules have been updated to match the overall coding style 
- added automatic lint fix script `npm run lint:fix`
- added Travis lint check

### CODE REVIEW

**Comment by cagataycivici** [comment]
Thank you, for a size of this change, we should do it on our side. Did you use ng lint --fix? to begin with?

**Comment by artemnih** [comment]
@cagataycivici yes, used `ng lint --fix`, then manually fixed what's left

**Comment by artemnih** [comment]
@cagataycivici my plan was to first fix lint, then add strong types everywhere. We are using this library in many of our projects and those types

**Comment by cagataycivici** [comment]
Thanks, due to amount of changes, I think it would be better to do this on our end. thank you.

**Pull request closed without merging**
