### PR TITLE
Adding class to body element when dialog is open

### PR DESCRIPTION
**Pull request by howlettt**
Adding ui-dialog-is-visible or ui-dialog-is-visible-modal class to the body element when dialog is open
#1625

### CODE REVIEW

**Comment by cagataycivici** [comment]
What is the purpose of manipulating body?

**Comment by howlettt** [comment]
The main purpose of adding a class to the body is so scrolling can be disabled on the background elements while a dialog is open. See #1625

**Comment by cagataycivici** [comment]
I see, instead we should make this easier by introducing a property like disableScroll="true|false".

**Comment by shaoshuai314** [comment]
This issue still exists in 2.0.5. Has the fix reverted in primeng?

**Comment by pedrotcm** [comment]
In IOS devices still scrolls the body, same using `[blockScroll]="true"` and `[modal]="true"`.

**Pull request closed without merging**
