### PR TITLE
WIP: Fixed #2242 | AutoComplete - Support optionLabel taking callback

### LINKED ISSUE #2242: Template for selected item in autocomplete (single selection mode)
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ x ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**

It's already possible to define an "item" template for the suggestions of the autocomplete, but this template is not used for the selected item. The selected item only looks at the "field" attribute, so it can only display 1 property of the object to which the ngModel is bound.

It's also possible to define a "selectedItem" template, but this template only seems to work in multiple selection mode (as stated in the documentation).

I've tried this example:

    <p-autoComplete [(ngModel)]="customer" [suggestions]="customerResults" (completeMethod)="searchCustomers($event)" field="name">
      <template let-customer pTemplate="item">
        {{customer.name}} {{customer.firstname}}
      </template>
      <template let-cusstomer pTemplate="selectedItem">
        {{customer.name}} {{customer.firstname}}
      </template>
    </p-autoComplete>

With this code my selected item only shows the "name" property of my customer-object. If I don't provide the field-property, my selected item is displayed as [object Object].

**Expected behavior**
I expect it to be possible to define a template for the selected item when the autocomplete is in single selection mode. It seems like I'm missing something as no one else seems to be asking this question, but I've tried everything I could find in the documentation, and nothing seemed to work.

**Minimal reproduction of the problem with instructions**

* **Angular version:** ~2.4.0

* **PrimeNG version:** 2.0.1

* **Browser:** [all ]

### PR DESCRIPTION
**Pull request by kyjus25**
### Defect Fixes
Fixes #2242 

### Summary
The docs described being able to pass a callback for when the user wants the label to be a concatenation of multiple fields in the option object but the component was not actually capable of doing so.

Additionally, the `field` property is deprecated, so the docs have been updated to use `optionLabel` instead.

### Example

```html
<p-autoComplete [optionLabel]="optionLabel" [suggestions]="filteredCountries" (completeMethod)="filterCountry($event)"  />
```
```ts
...
public optionLabel = (option: Country): string => {
  return `${option.label} is a cool country`;
}
```

### Feature Requests
Due to company policy, we are unable to accept feature request PRs with significant changes as such cases has to be implemented by our team following our own processes.
Smaller scaled feature implementations such as adding a property to a component will be considered for merging.

### CODE REVIEW

**Review by SoyDiego — APPROVED** [review]

**Review by cetincakiroglu — APPROVED** [review]
Thanks a lot for the effort and support!

**Comment by cetincakiroglu** [comment]
Could you please resolve the conflicts so we can merge it safely?

**Comment by cetincakiroglu** [comment]
Hi @kyjus25,

Could you please update your PR. Some files have been changed. Also if we implementing this one to the autocomplete, we also need to do the same for dropdown, multiselect, cascadeselect, selectButton, listbox.

**Comment by cetincakiroglu** [comment]
Closing due to inactivity.

**Pull request closed without merging**
