### PR TITLE
Calendar fix #1036 - handle min/max date change

### LINKED ISSUE #1036: Calendar model not updated if maxDate or minDate modifies the date
jQuery UI Datepicker modifies selected date if new min/maxDate is set and current date doesn't fit.  https://github.com/jquery/jquery-ui/blob/master/ui/widgets/datepicker.js#L1931. 

In this case jQuery Datepicker does not trigger 'onSelect' event and p-Calendar doesn't update it's model but the actual input value gets changed.

**Example:***

```
date = '13.03.2013';
maxDate = '23.03.2013';
```

```
<p-calendar [(ngModel)]="date" [maxDate]="maxDate" dateFormat="dd.mm.yy"></p-calendar>
```

image

Then we change: `maxDate = '11.03.2013'` and `console.log(date)`:

```
'13.03.2013'
```

but 
image

### PR DESCRIPTION
**Pull request by external-olgierd**
Make sure that date value is updated correctly and onSelect event is sent out with the new date whenever minDate or maxDate is updated and currently selected date falls outside the new range.

### CODE REVIEW

**Comment by cagataycivici** [comment]
Please describe the issue first.

**Comment by olo-b** [comment]
@cagataycivici this is as per #1036. Exact steps to reproduce:

1. Set minDate or/and maxDate on the calendar - for example 20.03.2017 and 30.03.2017 respectively
2. Select a date in range on calendar, for example 25.03.2017
3. Now change the minDate to be 26.03.2017 or the maxDate to be 24.03.2017 - the currently selected date no longer "fits" in the range.

This change makes sure that when step 3 happens, the currently selected date is updated and displayed correctly and also triggers onSelect event (as the date changes).

**Comment by britvik** [comment]
I'm not sure if this is really wanted behaviour. If min/max changes then your date gets set to min/max value and user may not notice this change.

See my issue #2437 with a pull request #2438. My solution makes date invalid if min/max changes so user can correct it (him/her)self.

**Comment by cagataycivici** [comment]
Please update the PR due to conflict and we'll review.

**Pull request closed without merging**
