### PR TITLE
Add programatic tree expansion

### PR DESCRIPTION
**Pull request by JakeSummers**
Requirements:

 * View the nodes that are currently expanded
 * Set what nodes are currently expanded
 * Ability to set the selected node recursively (so that all of its ancestors are also opened)

I have also updated the showcase to demonstrate this functionality.  Feel free to skip this commit, if it isn't valuable.

### CODE REVIEW

**Comment by JakeSummers** [comment]
This should resolve issue #261.

Additionally it should make implementing #682 very easy, either directly in your app or in the PrimeNg codebase.

**Comment by jayeffaar** [comment]
That would be pretty useful to us. We need to be able to automatically expand the parent of a newly created sub-folder, or restore a previous selection from user preferences, and auto-expand to it.

**Comment by cagataycivici** [comment]
Set target to beta15.

**Comment by JakeSummers** [comment]
Thanks!

**Comment by JakeSummers** [comment]
@cagataycivici - Do you want me to resolve the merge conflicts?  Any timeline on when this should be done 'review'?

**Comment by cagataycivici** [comment]
Just reviewed, one question what is the reason for following methods;

- expandToNode
- findPathToNode
- findPathToNodeRecursive

**Comment by JakeSummers** [comment]
> Just reviewed, one question what is the reason for following methods;
> 
> - expandToNode
> - findPathToNode
> - findPathToNodeRecursive

The `Tree.expandToNode` method isn't required, but it allows you to expand the entire tree to a specific node.  

Suppose that you have a tree like this: 

```
RootNode
 ├── Lunch
 │   ├── Drinks
 │   │    ├── OrangeJuice
 │   │    └── Coffee
 │   └── Food
 │        ├── Eggs
 │        ├── Bacon
 │        └── Toast
 └── Dinner
     ├── Drinks
     └── Food
```

Now suppose that you add `cream` to your `coffee`: 

```
RootNode
 ├── Lunch
 │   ├── Drinks
 │   │    ├── OrangeJuice
 │   │    └── Coffee
 │   │             └── Cream
 │   └── Food
 │        ├── Eggs
 │        ├── Bacon
 │        └── Toast
 └── Dinner
     ├── Drinks
     └── Food
```

`foodTree.expandToNode(creamNode)` allows us to easily expand the tree to show the new node.  Without this we need to find every node that is an ancestor of the creamNode and run `node.expanded = true`.

`findPathToNodeRecursive` is used by `expandToNode`.  It is a private method and not part of the API.  I created `findPathToNode` because I thought that it _could be_ a useful utility for other people, however I am fine with removing it.

**Comment by cagataycivici** [comment]
Thank you, I'd appreciate if you resolve the conflicts and I'll commit.

**Comment by JakeSummers** [comment]
@cagataycivici - Should be good to go.  Thanks for getting this in.

**Comment by cagataycivici** [comment]
Thank you for your contribution.

**Comment by JakeSummers** [comment]
Thanks for pulling that in!

**Comment by riscie** [comment]
Is this functionality still in the current release? I can't seem to find the newly added methods?

**Comment by riscie** [comment]
Aah, I see now
`// Currently only supported by tree.ts (not treeTable)`
I was looking to use this functionality with the treetable component.

**Comment by CodingYiyi** [comment]
@JakeSummers The above features has been removed?（expandToNode，findPathToNode，findPathToNodeRecursive）I can't seem to find the newly added methods（in ‘tree.ts’ file）

**Pull request merged**
