### PR TITLE
#3358 Added separator definition for excel

### PR DESCRIPTION
**Pull request by kenisteward**
###Defect Fixes
When submitting a PR, please also create an issue documenting the error.

#3358 True parsing of separator field for excel.

Very minor change.  I was able to test the changes in my local which worked.  

Should instead of using hard '\r\n' find a platform independent way in the browser to insert line endings.

@cagataycivici

### CODE REVIEW

**Comment by kenisteward** [comment]
@cagataycivici do note that at 
https://github.com/primefaces/primeng/blob/29ba431dd7fafb3ae79858156852407744d773cb/src/app/components/datatable/datatable.ts#L2383-L2395

It should definitely prefer operating system EOL as well instead of a hard '\n'

**Comment by kenisteward** [comment]
@cagataycivici  do you have time to merge this?

**Comment by cagataycivici** [comment]
screen shot 2017-10-03 at 11 18 56

Does not work for me on MAC

**Comment by kenisteward** [comment]
I'm confused by this.  It has sep=(no character) when it should with my changes at the very least have sep=,

you ran with my changes and not with the old suggestion right @cagataycivici  ?

**Pull request closed without merging**
