### PR TITLE
Resolved issue 10963 in panel menu

### LINKED ISSUE #10963: Panel menu with submenu expanded by itself when in sideBar
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

Test case:
https://angular-ivy-2l4wfz.stackblitz.io
https://stackblitz.com/edit/angular-ivy-2l4wfz?file=src/styles.css

**Current behavior**
PanelMenu's subMenu expanded by itself when placed inside sideBar 

**Expected behavior**
Submenu should not be expanded casue none clicked it...

**Minimal reproduction of the problem with instructions**
Scenario:
1. Click button with "Click me" label and do nothing more
2. Close sideBar by click X icon or by clicking somewhere outside sidebar
3. Click button "Click me" once again
4. "Menu two" is being expanded by itself with icon > wrongly indicating its state

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
I am using IntelliI IDEA

* **Angular version:** 5.X
Angular 12/13 doesn't matter

* **PrimeNG version:** 5.X
12.2.3 and 13.02 as well

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
I am using Chrome 96.0.4664.93

### LINKED ISSUE #12173: Panel menu with submenu expanded by itself when in sideBar #10963
### Describe the bug

PanelMenu's subMenu expanded by itself when placed inside sideBar
Continuation of https://github.com/primefaces/primeng/issues/10963

### Environment

Angular 14.2.10 so as PrimeNg 14.2.1

### Reproducer

https://stackblitz.com/edit/angular-ivy-2l4wfz?file=package.json

### Angular version

14.2.10

### PrimeNG version

14.2.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

14.17.3

### Browser(s)

All

### Steps to reproduce the behavior

1. Click button with "Click me" label and do nothing more
2. Close sideBar by click X icon or by clicking somewhere outside sidebar
3. Click button "Click me" once again
"M4. enu two" is being expanded by itself with icon > wrongly indicating its state

### Expected behavior

Submenu should not be expanded casue none clicked it...

### PR DESCRIPTION
**Pull request by NilavPatel**
Fixes #10963 
Fixes #12173

### CODE REVIEW

**Comment by NilavPatel** [comment]
Solution for defect 
https://github.com/primefaces/primeng/issues/10963

**Comment by rodolfocipagauta** [comment]
Sigo esperando la solución parta este defecto. 
Por el momento reemplace ese componente por el SLIDEMENU, por si a alguien le sirve como solución temporal.
Gracias.

**Comment by ColinNor** [comment]
Hi @NilavPatel will this problem be fixed in the near future?

**Comment by NilavPatel** [comment]
Not sure, I have created pull request with solution, but no one has review and merge it.

**Comment by Saganogemini** [comment]
Do you have any news on this one?... for us, this issue will define a go/no go with the latest version or keep PrimeNG version 9... the bad thing is that we bought the theme designer to do the migration, and now we are very disappointed since we have lots of panel menus inside sidebars :( !!

**Comment by NilavPatel** [comment]
@yigitfindikli would you please take a look at this merge request? Lots of peoples are facing this issue now.

**Comment by ColinNor** [comment]
I sent a mail to support and was told that this issue will be fixed in the next release

**Comment by Saganogemini** [comment]
Really, excellent news... I just can't wait

**Comment by AlexAvilaSantos** [comment]
```
<p-sidebar [(visible)]="visibleSidebar"  >
    <p-panelMenu *ngIf="visibleSidebar" [model]="modulos" autoDisplay="true"></p-panelMenu>
</p-sidebar>[](url)
```
lil trick, use same boolean for visible with ngif in panelMenu, have visual bug but works

**Review by cetincakiroglu — APPROVED** [review]

**Comment by cetincakiroglu** [comment]
Hi @NilavPatel,

Thanks a lot for your first-time contribution!
Don't forget to run **npm run build:check** command before pushing changes.

**Pull request merged**
