### PR TITLE
Feature #3496: Tooltip optionally take a TemplateRef

### LINKED ISSUE #3496: Template support for Tooltip
```
[x] bug report
[x] feature request 
[ ] support request 
```

I am currently using pTooltip and before that I used tooltip from ngx-bootstrap. I used to make templates and used them in my tooltip like this :  

```
<i class="fa fa-circle text-default" aria-hidden="true" [pTooltip]="defaultTooltip" tooltipPosition="top">
<ng-template #defaultTooltip>
    Something to display
</template>

```

Here it displays `[Object object]`. I wonder if it is possible to display what is actually inside my template.

### PR DESCRIPTION
**Pull request by kyjus25**
### Feature
resolves #3496

### Summary

Much like https://ng-bootstrap.github.io/#/components/tooltip/examples, pTooltip should take either a string or a Template Ref

### Gallery

Screenshot 2023-03-23 at 4 04 15 PM

### Feature Requests
Due to company policy, we are unable to accept feature request PRs with significant changes as such cases has to be implemented by our team following our own processes.
Smaller scaled feature implementations such as adding a property to a component will be considered for merging.

### CODE REVIEW

**Comment by kyjus25** [comment]
Set to WIP until I or someone can figure out why ngIfs and content interpolation doesn't render on first init but does after model changes

https://user-images.githubusercontent.com/6710794/227333386-a6d77ba0-da6f-423c-9793-e26e49f8b470.mov

**Comment by cetincakiroglu** [comment]
Wow, great feature and PR, thanks for the effort and support!

**Comment by kyjus25** [comment]
@cetincakiroglu conflicts resolved! Thanks!!!

**Comment by zerowww** [comment]
Any update about this PR ? Thanks :)

**Comment by kyjus25** [comment]
@cetincakiroglu @zerowww PR is updated and ready to go

**Comment by mertsincan** [comment]
Hi @kyjus25,

Sorry for the delayed response! Could you please update it? Then, I'll merge it asap.

Thanks a lot for your contribution!
Best Regards,

**Comment by kyjus25** [comment]
@mertsincan Updated!

**Comment by mertsincan** [comment]
Hi @kyjus25,

Thanks a lot for your contribution!

**Comment by bemes9226** [comment]
for tooltip templateref example in https://stackblitz.com/ need exaple here

**Pull request merged**
