### PR TITLE
feat(button): make standalone

### PR DESCRIPTION
**Pull request by alexciesielski**
Tracked in #15465 

Introduces the standalone API starting with the button component and directive. 

Once given the green light by @cetincakiroglu I will go ahead and open subsequent PRs making more components and directives standalone.

### CODE REVIEW

**Comment by cetincakiroglu** [comment]
Hi,

Thanks a lot for the effort and support, we'll review and test if it breaks anything during the build/deployment etc.

**Comment by kyjus25** [comment]
Super awesome you're even taking the time to break out CommonModule's import into importing the separate directives for smaller bundles. 🙏 Excited for this, thanks!

**Comment by cetincakiroglu** [comment]
Hi,

I've reviewed the button, ripple, shared & autofocus. I guess other files are unrelated.  Thanks a lot for the effort and support. Could you please remove unrelated files, rebase the master and update the PR so I can merge it safely? You can continue to make the rest of the components standalone. 

By doing so:
1-) Open an issue as `RelatedComponentName | Standalone`
2-) Link the issue with a PR.
3-) Be sure you pull the latest updates from the master branch. In your PR there are updates in autofocus but not the recent one which leads to conflicts.

**Comment by alexciesielski** [comment]
Hey, I rebased the branch and removed the changes to the `contextmenu.spec.ts`. Or do you mean anything else with "unrelated"? I tried to fix the usage in the tests as well but unforuntaly running `npm t` still throws a lot of errors so I'm not sure what to do here

**Comment by cetincakiroglu** [comment]
> Hey, I rebased the branch and removed the changes to the `contextmenu.spec.ts`. Or do you mean anything else with "unrelated"? I tried to fix the usage in the tests as well but unfortunately running `npm t` still throws a lot of errors so I'm not sure what to do here

Hi,

Yes, only the standalone related code. [A contributor](https://github.com/dobanisola-scottlogic) is currently working on tests.

**Comment by alexciesielski** [comment]
The tests can't declare the Button component themselves because that will throw errors. Or do you expect the contributor to adjust that as well?

**Comment by cetincakiroglu** [comment]
> The tests can't declare the Button component themselves because that will throw errors. Or do you expect the contributor to adjust that as well?
> 
> Edit: ok, will ignore them and remove the changes

You can fix import/export/declaration errors related to your update to make it work.

**Comment by alexciesielski** [comment]
Ok, that's what I've done ✅ all changes are related to standalone transition

**Comment by cetincakiroglu** [comment]
Hi @alexciesielski 

Thank you very much for your contribution. We are currently preparing for PrimeNG v18 and will make some internal component changes. Could you continue these PRs after we release PrimeNG 18? If you like, you can create issues and submit your PRs, and we can review them all after we release v18.

**Pull request merged**
