### PR TITLE
don't hide suggestions on self clicks (#2466)

### LINKED ISSUE #2466: AutoComplete hides when click inside input
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://www.primefaces.org/primeng/#/autocomplete

reproduce

**Current behavior**
Click on input when input was already in focus forces suggestions panel to hide.

**Expected behavior**
Suggestion should stay there

* **Angular version:** 2.x

* **PrimeNG version:** 2.x-4.x

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

### PR DESCRIPTION
**Pull request by evgd**
###Defect Fixes
#2466

### CODE REVIEW

**Comment by cagataycivici** [comment]
Will fix differently without dom

**Comment by evgd** [comment]
thanks!
to whom are not on master following code can be used as temporary patch:
```
@Component({
...
})
export class XyzComponent implements AfterViewInit, OnDestroy {

    @ViewChild(AutoComplete)
    public autocompleteComponent: AutoComplete;
	
	private unsubscribeOnDestory;

    public ngAfterViewInit() {
        this.autocompleteComponent.documentClickListener();
        this.unsubscribeOnDestory = this.renderer.listenGlobal('body', 'click', (evt: Event) => {
            if (evt.target === this.autocompleteComponent.inputEL.nativeElement) {
                return;
            }

            this.autocompleteComponent.hide();
        });
    }

    public ngOnDestroy() {
        this.unsubscribeOnDestory();
    }
}
```

**Comment by evgd** [comment]
@cagataycivici hi. do you think it's possible to get rid of global click listener? It looks like "blur" event will work just fine for case of hiding panel + additional hide call on suggestion "select".

**Comment by cagataycivici** [comment]
Nice catch, let me check tomorrow.

**Pull request closed without merging**
