### PR TITLE
Add gtag manager

### PR DESCRIPTION
**Pull request by gucal**
Add gtag manager. #13626

### CODE REVIEW

**Review by SoyDiego — COMMENTED** [review]
Maybe I'm wrong, but I leave here the same comment of @melloware in PrimeReact.

> Should we not render this script and run this code in Development mode? No sense in collecting analytics on local dev right?

I think apply the same case, right?, creating an environment variable.

Example of PrimeReact:

image

**Comment by melloware** [comment]
Agreed when running locally it is not necessary to track metrics 😀

**Comment by cagataycivici** [comment]
Agreed

**Comment by cagataycivici** [comment]
This should run in prod only, please create a new PR. @gucal @cetincakiroglu

**Pull request closed without merging**
