### PR TITLE
#15009 bug with not contains

### PR DESCRIPTION
**Pull request by juri-sinitson**
### Defect Fixes
Fixes the #15009 and adding unit tests for filtering.
Feel free to modify my code before merging when necessary.

### CODE REVIEW

**Comment by juri-sinitson** [comment]
# Remarks
1. I've covered the whole `filter` method of [TableService](https://github.com/primefaces/primeng/pull/16853/files#diff-2efed598926266f2db2ae53d90688c8b8c68532c441c541faba7bf0135d7453b) method and the most of the [FilterService](https://github.com/primefaces/primeng/pull/16853/files#diff-006d1a8477c7fc71531f0d682b9cd49180fbfeb6decab04278579c10053a389d)
2. Maybe it's reasonable to link the [unit tests](https://github.com/primefaces/primeng/pull/16853/files#diff-dc4e52bc95ec009f78c04632b32fe62afa44dc00cec2ae0ba9c01c3f839ddc51) of `TableService` to the documentation of the table filtering

**Comment by juri-sinitson** [comment]
Also let me know, if need to change something

**Comment by mertsincan** [comment]
Hi @juri-sinitson, thanks a lot for your contribution! Can you please resend your PR for v18 branch? Also, please don't change the folder structure (table.service) or add your IDE setting. We'll update folders after the 19 release.

**Comment by juri-sinitson** [comment]
Hi @mertsincan,

sorry for a big delay. I've noticed that the version 19 is out and it's a part of `master` by an appropriate tag.

For me it looks like it's now better to resend a PR for master instead of v18. 
If I'm wrong just let me know for which branch I should resend the PR. Also let me know if you have some other wishes.

I've just rebased my branch to the current master.
I've also considered your remarks about not changing the folder structure now and not adding IDE settings.
So I'm going to resend my PR later today.

**Comment by juri-sinitson** [comment]
@mertsincan 
I've resent the PR [here](https://github.com/primefaces/primeng/pull/17165).

**Pull request closed without merging**
