### PR TITLE
Adding property [showClear] in p-autocomplete to let user clear by clicking easily

### LINKED ISSUE #3660: Clear icon for AutoComplete
when selected item contains many character,we need typewrite BackSpace key too many times,it's not convenient!

### PR DESCRIPTION
**Pull request by augustobreno**
###Defect Fixes
#3660 

###Feature Requests
Just add [showClear] option do p-autocomplete, appending the same behavior as found in p-dropdown, letting user clear current selected item easily.

https://www.loom.com/share/38216dbe1cab47e3895d91035fc25e9b

### CODE REVIEW

**Comment by scurk1415** [comment]
Would be nice if this gets merged soon (maybe in the next minor release?)

**Comment by luizmlpascoal** [comment]
I really need on v.8

**Comment by vochitan90** [comment]
Look like this is not merged to latest release? anyone have any updated pls!

**Comment by vinothvkr** [comment]
Waiting for this. Please someone merge this request.

**Comment by cetincakiroglu** [comment]
Hi @augustobreno,

This feature already exists in PrimeNG v15, closing the PR.

Thanks for your effort and support!

**Pull request closed without merging**
