### PR TITLE
[Table] Third click to undo sorting

### PR DESCRIPTION
**Pull request by ranthonissen**
Implements #8013 to undo the sorting of a table on the third click on the column:
* works for both single as multiple sorting
* first 2 click sort ascending / descending
* 3rd click sorts the table data in its default order

### CODE REVIEW

**Comment by cagataycivici** [comment]
One of those things that we prefer to be implemented on our side, thank you.

**Comment by loxy** [comment]
> One of those things that we prefer to be implemented on our side, thank you.

Because you are faster?

**Comment by denversynchro** [comment]
How do you turn on unsort on 3rd click?

**Comment by gianluca-moro** [comment]
So, has this been implemented yet?

**Comment by ranthonissen** [comment]
@gianluca-moro No, they totally ignored it and never cared to implement it themselves

**Pull request closed without merging**
