### PR TITLE
Fix issue #2381 File Upload component clean the selected file when user click on "Cancel" on the file choose window in IE11

### PR DESCRIPTION
**Pull request by davidkirolos**
###Defect Fix
Fix issue **#2381**

### CODE REVIEW

**Comment by cagataycivici** [comment]
Please update the PR due to conflict.

**Comment by cot-dkirolos** [comment]
PR Updated, Please re open it.

**Comment by davidkirolos** [comment]
PR Updated, Please re open it.

**Comment by cagataycivici** [comment]
Tracked at #3082

**Pull request closed without merging**
