### PR TITLE
Custom sort function on load is not invoked

### PR DESCRIPTION
**Pull request by ryanwawr**
Added to fix issue #553 . If the sort field for a table is a column with a custom sort function, the 'customSort' event will not be emitted when the table is first loaded, since 'sortColumn' is not set. 

I added a line to the condition in sortSingle() that will also emit the 'customSort' event if
1) 'SortField' is set
2) The column whose 'field' property matches 'sortField' has its 'sortable' field set to 'custom'

### CODE REVIEW

**Comment by cagataycivici** [comment]
But sortColumn still won't be set so how could the sortFunction be emitted?

**Comment by cagataycivici** [comment]
Please review  https://github.com/primefaces/primeng/commit/583e89160e64b4db0f33ba9d61d3f4360a4d7a60

It sets it before sorting if sortColumns is not available on load.

**Comment by ryanwawr** [comment]
Ah, you're right. I missed setting sortColumn, but it looks like your commit should resolve the issue.  Thanks!

**Comment by JiroDan** [comment]
Doing this in onDoCheck means that you must check to see if the columns are bound first;
634:          if(!this.sortColumn && this.columns) {

Otherwise it throws, Cannot read property 'find' of undefined: 635

**Pull request closed without merging**
