### PR TITLE
Row selection should be on a tap event instead of a touchstart

### PR DESCRIPTION
**Pull request by samuellaplante**
If the event is on a touchstart the handler is called as soon as the user touch the screen. This may be not the expected behaviour on mobile, because if the user is trying to scroll the content of the table, the event is fired to soon and this might not be the intention of the user.

### CODE REVIEW

**Comment by samuellaplante** [comment]
#1666

**Comment by cagataycivici** [comment]
This gives an error like hammer.js not loaded, it may cause similar problems to users.

**Comment by cagataycivici** [comment]
Will reconsider if more users request it.

**Comment by sgomanf** [comment]
same issue, as soon as the user touch the screen, it select the row

**Pull request closed without merging**
