### PR TITLE
Fix typo "seperator" instead of "separator"

### LINKED ISSUE #14074: Fix typo "seperator" in all the project
### Describe the bug

We have in all the primeng project the typo `seperator` instead of `separator`

image

### Environment

-

### Reproducer

_No response_

### Angular version

Last version

### PrimeNG version

16.7.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

Last version

### Browser(s)

_No response_

### Steps to reproduce the behavior

-

### Expected behavior

-

### PR DESCRIPTION
**Pull request by SoyDiego**
Fix #14074 

Fix typo `seperator` instead of `separator`.

### CODE REVIEW

**Comment by ashikjs** [comment]
@SoyDiego  Can you fixed conflicts.

**Comment by SoyDiego** [comment]
> @SoyDiego Can you fixed conflicts.

Done! :)

**Comment by ashikjs** [comment]
@SoyDiego  If you every time merge master branch then it create a log/commit. If you rebase master  branch then it will longer generate any log or commit. You can try it, it make  git log more clear and clean.

Simple way you can do this just , take pull on your local master branch and checkout you branch then `git rebase master` btw  if you have multiple commit then it also make harder to rebase but for sinagle commit it work like awesome.

**Comment by SoyDiego** [comment]
> @SoyDiego If you every time merge master branch then it create a log/commit. If you rebase master branch then it will longer generate any log or commit. You can try it, it make git log more clear and clean.
> 
> Simple way you can do this just , take pull on your local master branch and checkout you branch then `git rebase master` btw if you have multiple commit then it also make harder to rebase but for sinagle commit it work like awesome.

Thanks, I will try next time

**Review by cetincakiroglu — APPROVED** [review]

**Pull request merged**
