### PR TITLE
Fix for #7008 p-calendar not disabling months outside of minDate/maxDate with view="month" 

### PR DESCRIPTION
**Pull request by PrestonJordan**
This will fix the issue reported in #7008

### CODE REVIEW

**Comment by harish0000** [comment]
is this issue fixed ?

**Comment by PicOLinO** [comment]
@harish0000 Latest PrimeNG v8.0.0 still has this issue.

**Comment by skylarkgit** [comment]
When is it going to merge? I was about to make a new PR but found this.

**Comment by cagataycivici** [comment]
Seems to be fixed by my colleague already, see original issue.

**Pull request closed without merging**
