### PR TITLE
DataTable: Add ability to specify class to use on the table tag, and the ability to specify the class to use if the table is responsive.

### PR DESCRIPTION
**Pull request by shahmirn**
Add ability to specify class to use on the table tag, and the ability to specify the class to use if the table is responsive.

### CODE REVIEW

**Comment by cagataycivici** [comment]
Why not just [class]="tableStyleClass" ?

**Comment by shahmirn** [comment]
@cagataycivici Changed code to use tableStyleClass and added documentation.

**Comment by cagataycivici** [comment]
Thank you, we'll provide tableStyleClass but rather keep the responsive class as fixed for now.

**Comment by cagataycivici** [comment]
See #1155

**Pull request closed without merging**
