### PR TITLE
P-Table - Column resize not working as expected

### PR DESCRIPTION
**Pull request by biswasSaumyadip**
**Defect Fixes**
#12183

https://user-images.githubusercontent.com/72658964/235771905-a8bc2798-bb4f-44d4-a510-ffaa38015ba4.mp4

### CODE REVIEW

**Comment by Assassinationrogue** [comment]
https://user-images.githubusercontent.com/72658964/235771665-50f3da45-ef43-4bf5-9449-3d0514a5251c.mp4

**Review by jhcpeixoto — APPROVED** [review]

**Comment by jhcpeixoto** [comment]
@cetincakiroglu Any update about this PR?

**Comment by jhcpeixoto** [comment]
When i change column size he change other columns, it need keep others columns 
**columnResizeMode="expand"**

**Review by cetincakiroglu — APPROVED** [review]

**Comment by PranKe01** [comment]
Please make sure it also works with columnResizeMode="fit".

**Comment by biswasSaumyadip** [comment]
> Please make sure it also works with columnResizeMode="fit".

Yeah code wise I have taken care of that one too.

**Pull request merged**
