### PR TITLE
Add focus event listener to autocomplete input

### PR DESCRIPTION
**Pull request by brtnshrdr**

### CODE REVIEW

**Comment by brtnshrdr** [comment]
You can just get the Autocomplete instance (using ViewChild), then access the focus method itself

**Comment by brenikindhi** [comment]
Can you please give an example for this. I have a requirement to show list onFocus. I mean need to call a method in my custom component to get the list.

Thanks for your help.

**Comment by brtnshrdr** [comment]
First just get the AutoComplete instance like this:
```@ViewChild(AutoComplete) private autoComplete: AutoComplete;```

Then just call this function when you want to focus it:
```this.autoComplete.input.focus()```

**Comment by brtnshrdr** [comment]
Sorry. That is to actually GAIN focus on the input. It looks like there isn't a focus output that you can easily access. This pull request could technically still be useful then!

**Comment by brenikindhi** [comment]
Yeah, Is there any way to do it? Or shall I raise any request for this?

**Comment by brtnshrdr** [comment]
It doesn't look like it. I'd create an issue for this. The change is fairly simple (I did it in this pull request, but it's very out of date. If I find time, I'll update it)

**Comment by brenikindhi** [comment]
Please update included version.

Thanks for your help. Appreciated.

**Comment by brenikindhi** [comment]
Users are not accepting to go live next month without this functionality. Can you please expedite this.

**Comment by brenikindhi** [comment]
Hi Nick, Did you get a chance to merge your code to any of the PrimeNg release.
Can you please let us know the included version of this. This has become critical for us.

Thanks for your help.

**Pull request closed without merging**
