### PR TITLE
fix: #13007 || AutoComplete control inappropriately fires onClear eve…

### PR DESCRIPTION
**Pull request by ashikjs**
FIx: #13007 

## Explanation 

Issue was `onClearEvent` fire when `forceSelection` is ` true` and user select from suggestion list 

Excepted behavior is should not fir when user select from suggestion list.

Currently we check  **forceSelection** every time when input change and  it's true .

Main problem is option select event fire after input change event. 

So I write a function name **onForceSelectOrClearInput** with existing code. Then **onInputChange** I call this function if user don't select suggestion option. For this case i did wait 200ms to fire next event **selectItem** because when this **selectItem** fire I set value true of `isSuggestionOptionSelect`  variable. 

## Extra Code

Github PR Checker give me error when it run Code format. 
So I solve it by remove on space from `src/app/components/table/table.ts`

### CODE REVIEW

**Comment by ashikjs** [comment]
@mertsincan and @gucal  hi, can you please check this PR. Thanks in advance.

**Comment by cetincakiroglu** [comment]
Hi @ashikjs 

Could you please update the PR and resolve the conflicts so we can merge safely?

**Comment by ashikjs** [comment]
@cetincakiroglu  I re-check this bug but can not reproduce it so i belive it's already solved.

**Comment by cetincakiroglu** [comment]
> @cetincakiroglu I re-check this bug but can not reproduce it so i belive it's already solved.

Thanks for the feedback, probably solved at one point in the history. I'm closing this one.

**Pull request closed without merging**
