### PR TITLE
fix Dropdown: Tab key not navigating between fields #13664

### LINKED ISSUE #13664: Dropdown: Tab key not navigating between fields
### Describe the bug

Using a angular app i upgrade primeng to version 16.3.1 and after that when i filling a form with dropdown fields i can't navigate between fields using tab key the focus get stucked on the dropdown, i have downgraded primeng to version 16.2.0 and the problem desapear.

### Environment

Angular app v 16.x.x, primeng 16.3.1

### Reproducer

_No response_

### Angular version

16.2.0

### PrimeNG version

16.3.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.17.1

### Browser(s)

Chrome 116

### Steps to reproduce the behavior

Any form with many fields and at least one dropdown, click on the dorpdown and try to navigate betwwen fields using tab key.

### Expected behavior

navigate between fields

### PR DESCRIPTION
**Pull request by atamansv**
Call preventDefault only for Escape key

### Defect Fixes
Fix #13664 Dropdown: Tab key not navigating between fields

### CODE REVIEW

**Review by SoyDiego — APPROVED** [review]

**Comment by SoyDiego** [comment]
Thanks for your PR.
Please add in your first comment `Fix #13664` to link this PR to the issue and when PrimeNG Team approve it, will close automatically.

**Comment by atamansv** [comment]
Fix https://github.com/primefaces/primeng/issues/13664

**Comment by atamansv** [comment]
@SoyDiego, maybe you can help?

**Comment by cetincakiroglu** [comment]
Hi,

We're currently doing accessibility implementation to all components and by doing that we're refactoring and reworking the components and their working logic from scratch. That one is fixed already during the dropdown accessibility implementation process and the fix is in the accessibility. We're planning to release it next Wednesday. Even though I accept your PR, it'll be removed when merging the accessibility branch. Because of that, I'm closing this PR. Thanks for your effort and support to make PrimeNG better!

**Pull request closed without merging**
