### PR TITLE
Fixed #8801 - Multiple DynamicDialogs are not closing programmatically

### LINKED ISSUE #8801: Multiple DynamicDialogs are not closing programmatically
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/github/primefaces/primeng-issue-template

**Current behavior**

When two dynamic dialogs are open with the same component, the first one (the one under the second one) cannot be closed progammatically.

**Expected behavior**

All dialogs should be allowed to be closed programmatically.

**Minimal reproduction of the problem with instructions**
- Go on stackblitz: https://stackblitz.com/edit/angular-primeng-multiple-dynamic-dialog-close-bug
- Click on the "Test me" button.
- Two dynamic dialogs of the same component open with different content
- Click on the "Close" button on the upper most dialog (it closes)
- Click on the "Close" button on the other dialog (nothing happens)

**What is the motivation / use case for changing the behavior?**
Two dynamic dialogs created with the same component should be programmatically closable.

**Please tell us about your environment:**

* **Angular version:** 9.1.3

* **PrimeNG version:** 9.0.6

* **Browser:** all
 
* **Language:** all

### PR DESCRIPTION
**Pull request by mrdlink**
###Defect Fixes
Fixes bug when opening multiple dynamic dialogs from a single service and then trying to close them.
Multiple dynamic dialogs would not close at all, only the last opened dynamic dialog would close properly.
With this fix all opened dynamic dialogs now close properly.

### CODE REVIEW

**Comment by mikaelboff** [comment]
@cagataycivici

**Comment by mikaelboff** [comment]
@cagataycivici , will it be released to 9.x versions?

**Comment by cagataycivici** [comment]
Set to 10.0.2.

**Comment by mikaelboff** [comment]
Excuse me, will it be released to 9.x versions?

**Comment by yigitfindikli** [comment]
Hi @mrdlink,
Thanks for your contribution.

**Comment by yigitfindikli** [comment]
@mikaelboff Yes, It will be added to v9-lts.

**Pull request merged**
