### PR TITLE
Default to no button text when label is not set.

### PR DESCRIPTION
**Pull request by BustyLoli-Chan**
This is a pull request to fix the issue demonstrated by this Plunkr.
http://plnkr.co/edit/dSx8dBkXUQJXWtZHIOvc?p=preview

I've modified this line:

primeng/src/app/components/button/button.ts

Line 34 in d06afd8
 labelElement.appendChild(document.createTextNode(this.label||'ui-btn')); 

To allow for situations in which an end user would prefer to just have a button without a label so that they may edit the actual HTML inside of the button tag.

It is currently known by issue #1657 that you can currently hide this text with the following styling

.ui-button-text-only .ui-button-text{
    display: none !important;
}

but this seems like it should be unnecessary.

### CODE REVIEW

**Comment by sudheerj** [comment]
It looks like that the PR includes other changes as well. Can you please recheck it.

**Comment by BustyLoli-Chan** [comment]
The other commit merged in the latest primeNg stuff from Master because I hope it would fix the Travis build. It didn't. If you look at the files changed tab though there is only one file that is different from Master.

**Comment by cagataycivici** [comment]
We still some sort of content otherwise button shrinks, I'll add a css solution instead.

**Comment by BustyLoli-Chan** [comment]
Alright, sounds good. I just hope it fixes it 😱

**Pull request closed without merging**
