### PR TITLE
fixed #3046: .ui-state-filled class was not set initially for pInputT…

### LINKED ISSUE #3046: .ui-state-filled not set initially when using OnPush and [value] binding
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/aOzYbfRSrxc0G0NuiISL?p=preview

**Current behavior**
when using OnPush, filled inputs with pInputText don't initially have the ui-state-filled css class when setting the value with the [value] binding

**Expected behavior**
the input should have the ui-state-filled css class

**Minimal reproduction of the problem with instructions**
1. open the plunkr above
2. inspect the input
3. it does have a value, but it doesn't have the ui-state-filled css class (background is red, if the class is missing)

**What is the motivation / use case for changing the behavior?**
because it is a bug and it breaks ultima-ng

**Please tell us about your environment:**
Windows 8.1

* **Angular version:** 4.1.3

* **PrimeNG version:** 4.0.3

* **Browser:** all 
 
* **Language:** probably all

### PR DESCRIPTION
**Pull request by saithis**
…ext, pInputTextArea and pPassword when using ChangeDetectionStrategy.OnPush with value or ngModel binding

### CODE REVIEW

**Comment by cagataycivici** [comment]
Have you tested it in a reactive form?

**Comment by saithis** [comment]
I can't remember as it was over 3 months ago... but the bug doesn't exist when using reactive forms, only with value/ngModel binding. Also I think the  @Optional() was, because the NgModel injection only works when unsing ngModel binding. So for reactive forms it should be undefined, as it is with the [value] binding and so it shouldn't break it.

**Comment by saithis** [comment]
@cagataycivici What is your problem with this PR? Why does it take over 6 months now to get this reviewed/merged? The uuuuultra slow response time doesnt really encourage us to buy another premium template for the next project :/

**Comment by cagataycivici** [comment]
I just hope for a better solution.

**Comment by saithis** [comment]
I know that the solution isn't pretty, but I spent a whole day to find a better solution and didn't find any... so is it better to what for a solution that may never come, than to fix this bug already and releave us and maybe others from all the workarounds for this bug that clutter our codebase?

**Comment by cagataycivici** [comment]
My answer is super fast now, sorry sometimes lot of things get in our routine preventing a PR to proceed. Let me work on this again and get back to you. Again excuses for the unusual delay, it is one of those things that stuck and not move on.

**Comment by cagataycivici** [comment]
We need a solution to cover both reactive and template driven forms.

**Pull request closed without merging**
