### PR TITLE
fixed #3046: .ui-state-filled class was not set initially for pInputT…

### LINKED ISSUE #3046: .ui-state-filled not set initially when using OnPush and [value] binding
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/aOzYbfRSrxc0G0NuiISL?p=preview

**Current behavior**
when using OnPush, filled inputs with pInputText don't initially have the ui-state-filled css class when setting the value with the [value] binding

**Expected behavior**
the input should have the ui-state-filled css class

**Minimal reproduction of the problem with instructions**
1. open the plunkr above
2. inspect the input
3. it does have a value, but it doesn't have the ui-state-filled css class (background is red, if the class is missing)

**What is the motivation / use case for changing the behavior?**
because it is a bug and it breaks ultima-ng

**Please tell us about your environment:**
Windows 8.1

* **Angular version:** 4.1.3

* **PrimeNG version:** 4.0.3

* **Browser:** all 
 
* **Language:** probably all

### PR DESCRIPTION
**Pull request by saithis**
…ext, pInputTextArea and pPassword when using ChangeDetectionStrategy.OnPush with value or ngModel binding

### CODE REVIEW

**Comment by saithis** [comment]
I considered fixing it with
```
    ngAfterViewInit(){
      setTimeout(() => {
        this.updateFilledState();
        this.cd.markForCheck();
      });
    }
```
but that resulted in a noticeably flicker for the user.

**Comment by cagataycivici** [comment]
This is hard to track with +85 −6, please provide a PR with only the actual line changes, seems to be an issue with new lines.

**Comment by saithis** [comment]
whitespaces are the issue, not newlines. the code has useless whitespaces all over the places, which are removed by my editor. I'll fix it later today.

**Comment by saithis** [comment]
New PR here: https://github.com/primefaces/primeng/pull/3647

**Pull request closed without merging**
