### PR TITLE
Added listener function check in ngOnDestroy, fixes primefaces/primeng#2149

### PR DESCRIPTION
**Pull request by andrii-oleksyshyn**

### CODE REVIEW

**Comment by cagataycivici** [comment]
Will merge manually, thanks.

**Comment by andrii-oleksyshyn** [comment]
Hi, are you going to add it to 2.x build?

**Comment by andrii-oleksyshyn** [comment]
Hello, do you have any updates?

**Comment by cagataycivici** [comment]
No plans to do another 2.x build at the moment.

**Pull request closed without merging**
