### PR TITLE
Added customSizes to fileupload component

### LINKED ISSUE #13398: FileUpload: allow file size units internationalization
### Describe the feature you would like to see added

Define the formatSize units in the language I want.

### Is your feature request related to a problem?

I need to display file size units in French language:

['o', 'ko', 'Mo', 'Go', 'To', 'Po', 'Eo', 'Zo', 'Yo']

### Describe the solution you'd like

Have an Input parameter to define formatSize

### Describe alternatives you have considered

_No response_

### Additional context

_No response_

image

### PR DESCRIPTION
**Pull request by SoyDiego**
closes #13398

Added `customSizes` to personalize the units to display. This allow the internationalization
By default is: `['B', 'KB', 'MB', 'GB', 'TB', 'PB', 'EB', 'ZB', 'YB']`.

## Example with french units: `['o', 'ko', 'Mo', 'Go', 'To', 'Po', 'Eo', 'Zo', 'Yo']`

fileupload customsizes

### Added documentation

image

### CODE REVIEW

**Comment by SoyDiego** [comment]
> Thanks for the solution.
> 
> Just one remark: line 836 is missing the translation. I suggest this modification:
> 
> ```
>     const sizes = this.customSizes || ['B', 'KB', 'MB', 'GB', 'TB', 'PB', 'EB', 'ZB', 'YB'];
>     if (bytes === 0) {
>         return `0 ${sizes[0]}`;
>     }
> 
>     const k = 1000;
>     const dm = 3;
> ```

Thanks @ajjp,I forgot that part. Now I added :)

**Comment by mertsincan** [comment]
Hi @SoyDiego, 

I think you can add a locale option for it. https://github.com/primefaces/primelocale
```
en = {
...
   fileSizeTypes: ['B', 'KB', 'MB', 'GB', 'TB', 'PB', 'EB', 'ZB', 'YB']
}

fr = {
...
   fileSizeTypes: ['o', 'ko', 'Mo', 'Go', 'To', 'Po', 'Eo', 'Zo', 'Yo']
}
```

**Comment by SoyDiego** [comment]
> Hi @SoyDiego,
> 
> I think you can add a locale option for it. https://github.com/primefaces/primelocale
> 
> ```
> en = {
> ...
>    fileSizeTypes: ['B', 'KB', 'MB', 'GB', 'TB', 'PB', 'EB', 'ZB', 'YB']
> }
> 
> fr = {
> ...
>    fileSizeTypes: ['o', 'ko', 'Mo', 'Go', 'To', 'Po', 'Eo', 'Zo', 'Yo']
> }
> ```

Hi, that is new, right?

> Hi @SoyDiego,
> 
> I think you can add a locale option for it. https://github.com/primefaces/primelocale
> 
> ```
> en = {
> ...
>    fileSizeTypes: ['B', 'KB', 'MB', 'GB', 'TB', 'PB', 'EB', 'ZB', 'YB']
> }
> 
> fr = {
> ...
>    fileSizeTypes: ['o', 'ko', 'Mo', 'Go', 'To', 'Po', 'Eo', 'Zo', 'Yo']
> }
> ```

Hi, I don't think so because currently you assign that values and you cannot change.
With this PR you will.

image

But maybe this is another thing that you should talk as a team because in PrimeVue and PrimeReact you should implement too. It's a new feature and I don't know if you want this feature.

**Comment by mertsincan** [comment]
Hi @SoyDiego,

Yes, it should be a new locale option. Please see our default locale options;
https://github.com/primefaces/primeng/blob/master/src/app/components/api/primengconfig.ts#L19

Users can automatically change the value of 'fileSizeTypes' by selecting any locale. I don't think there is a need for a separate FileUpload attribute for this.

Note: The change of 'dayNames' in Calendar according to locale can give you a clue. We would be grateful if you could send a PR to PrimeNg and others. I'll merge them ;)

Thanks a lot for your contribution! We really appreciate your PRs 🚀
Best Regards,

**Comment by mertsincan** [comment]
A new PR would be better ;) Thank you so much for your effort!

**Pull request closed without merging**
