### PR TITLE
a11y: Add ariaLabel support for calendar

### PR DESCRIPTION
**Pull request by Foxandxss**
This PR should fix the issue I just created. Please ping me if anything extra needs to be done 👍 

Fixes: #13319

### CODE REVIEW

**Comment by SoyDiego** [comment]
I did something similar for p-menu component but the PrimeNG right now it's working in all about accessibility following the same rules of PrimeVue
Here you can see also the reply that I have received in that moment. https://github.com/primefaces/primeng/pull/13167#issuecomment-1608446037.

Also you have this message in Calendar Component at the bottom of the page.

image

**Comment by Foxandxss** [comment]
Any update on this? I see the conflict. I don't mind rebasing but no idea if you want this to be merged.

**Comment by SoyDiego** [comment]
> Any update on this? I see the conflict. I don't mind rebasing but no idea if you want this to be merged.

They are working in accessibility things and in theory Wednesday they review some PRs. Resolve the conflict if you can and maybe today you have luck if your PR ok

**Comment by Foxandxss** [comment]
Oh, it has been fixed already. Good #13990

**Pull request closed without merging**
