### PR TITLE
fix autocomplete panel width when [appendTo]='body'

### PR DESCRIPTION
**Pull request by andrea-spotsoftware**
Related to issue #2929, inspired by dropdown

### CODE REVIEW

**Comment by andrea-spotsoftware** [comment]
any chance to accept and publish this?

**Comment by andrea-spotsoftware** [comment]
@cagataycivici I'm evaluating this suite for a customer, and unfortunately I need this fix to use it in production. Is it possible to have a check on this fix?

**Comment by cagataycivici** [comment]
Will do it a bit differently

**Comment by cagataycivici** [comment]
https://github.com/primefaces/primeng/commit/b0c5b14ed1128d7309f045a9f1dee88bdbccdd85

**Pull request closed without merging**
