### PR TITLE
fix(primeng/p-tabview): show the `forward` button when necessary

### LINKED ISSUE #11684: TabView: Next-button occurs also if nothing is to scroll
### Describe the bug

If `scrollable` is activated on `tabView` then the next-button occurs also if there is enough space for all tabs and nothing is to scroll.

### Environment

macos 12.4

### Reproducer

https://stackblitz.com/edit/github-7hs7o5?file=src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.component.ts

### Angular version

14.0.4

### PrimeNG version

14.0.0-rc1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.15.1

### Browser(s)

_No response_

### Steps to reproduce the behavior

_No response_

### Expected behavior

Next button should only occur if there is not enough space for all tabs.

### PR DESCRIPTION
**Pull request by volvachev**
###Defect Fixes
fix #11684

### CODE REVIEW

**Review by cetincakiroglu — COMMENTED** [review]
Hi @volvachev ,

Thanks for your effort and support.
I have a question about this PR, what problem is exactly solved?
If the aim is to hide the forward arrow when the screen is big enough to fit all scrollable items. I don't see any difference in my browser when I shrink the screen, the forward arrow is still there even though there is nothing to scroll. Could you guide me, I'm a bit confused.

**Comment by volvachev** [comment]
> Hi @volvachev ,
> 
> Thanks for your effort and support. I have a question about this PR, what problem is exactly solved? If the aim is to hide the forward arrow when the screen is big enough to fit all scrollable items, I don't see any difference in my browser when I shrink the screen, the forward arrow is still there even though there is nothing to scroll. Could you guide me, I'm a bit confused.

Hi,
This fix relates to the first initialization of the component. When the screen is large, but an unnecessary button is displayed.

There is an example on stackblitz in the issue.

**Comment by cetincakiroglu** [comment]
Hi @volvachev,

I reviewed your PR and there is a defect in it. It only works on the first load or refresh, it fails if I shrink the screen. Could you please solve that?

**Comment by volvachev** [comment]
> Hi @volvachev,
> 
> I reviewed your PR and there is a defect in it. It only works on the first load or refresh, it fails if I shrink the screen. Could you please solve that?

Hi @cetincakiroglu,
I've updated the PR, now the redraw happens when the window is resized as well.

**Review by cetincakiroglu — APPROVED** [review]
Hi @volvachev,

Thanks for your support and effort! 
I've reviewed your PR and it works perfectly. However, since there are changes in primeng/utils folder we need to discuss this enhancement as a team to decide whether to implement it or to make some changes.

**Comment by majkers** [comment]
There is one more thing that might be fixed. If we have many tabs and lets say that the last one in selected, when shrinking a window both tabMenu and tabView components do not scroll to seleted tab. One have to do it manually. My workaround for it is to not only update button state when listening to resize event method but in;
- tabMenu call ngAfterViewInit() which has also  methods:  this.updateInkBar(); and this.initAutoScrollForActiveItem();
- tabView call all this: this.tabViewRef.updateButtonState(); this.tabViewRef.updateInkBar(); this.tabViewRef.updateScrollBar(this.activeIndex); this.tabViewRef.cd.detectChanges();
Also I have a debounceTime(500) in window resize event listener to avoid reacting on every change. I explained everything in https://github.com/primefaces/primeng/issues/11684

**Comment by cetincakiroglu** [comment]
Hi @volvachev ,

Reverted the pull request in https://github.com/primefaces/primeng/pull/11719 due to it breakes npm run build:lib 

Thanks for the effort and support!

**Pull request merged**
